### ISSUE TITLE
[Promo] Official Quart logo

### ISSUE THREAD

**Issue by koddr** [pgjones/quart#1]
Hi, @pgjones 

I want to start this disqus because it's important to promotion and visual identity. Good Python framework need good visual stuff! So, I have some ideas about official `Quart` logo and give you them for free :) Look please.

## Handwritten logo

<img width="100%" alt="screen shot 2017-12-04 at 12 15 07" src="https://user-images.githubusercontent.com/11155743/33544700-d47d95fa-d8ec-11e7-8a09-88719a6c598f.png">

Font: Amarillo (this's a paid font, but I already bought it)
Color: RGB 214, 11, 82 (HEX #d60b52)

## Literal with text

<img width="100%" alt="screen shot 2017-12-04 at 12 43 03" src="https://user-images.githubusercontent.com/11155743/33545973-cc85a960-d8f0-11e7-9228-99f1c7a708e4.png">

Font: Lifehack Basic (this's a paid font, but I already bought it) + Open Sans (or similar)
Color: RGB 45, 46, 131 (HEX #2d2e83) + similar dark color, like #333333

**Comment by pgjones** [comment]
Thanks @koddr, these are a really nice start. Ideally I would like the logo to reference the bottle theme Python web frameworks have going, for example Flask has a flask,
![image](https://user-images.githubusercontent.com/1391482/33573403-9a2733b6-d92d-11e7-9b9b-e6f65ac9c7a0.png)

and Bottle has a bottle 
![image](https://user-images.githubusercontent.com/1391482/33573632-476e26c4-d92e-11e7-862a-e5d17e6b1884.png)

So could you incorporate a Quart glass somehow?

Also how would you propose licensing the logo? A creative commons or similar to [Flask](http://flask.pocoo.org/docs/0.12/license/#artwork-license)?

**Comment by koddr** [comment]
Oh, I understand what you mean as `Quart`:

> The quart (abbreviation qt.) is an English unit of volume equal to a quarter gallon. It is divided into two pints or four cups. Historically, the exact size of the quart has varied with the different values of gallons over time and in reference to different commodities. Presently, three kinds of quarts remain in use: the liquid quart and dry quart of the US customary system and the imperial quart of the British imperial system. All are roughly equal to one metric liter.

So, can you give me more words for more associates?

**Comment by pgjones** [comment]
Oh right, I thought it was a distinct bottle type as well (rather than just a volume), that said the name is distinctive. In which case maybe a bottle (ideally that looks like it holds a quart :p), that looks good is good enough?

**Comment by koddr** [comment]
@pgjones yep. I make some sketches with bottle (and around):

<img width="320" alt="screen shot 2017-12-05 at 14 11 37" src="https://user-images.githubusercontent.com/11155743/33604265-5163d820-d9c6-11e7-8bd2-d1fa512bc7d8.png">

<img width="320" alt="screen shot 2017-12-05 at 14 25 57" src="https://user-images.githubusercontent.com/11155743/33604789-47901f6e-d9c8-11e7-9b61-18c4cfb44b8d.png">

<img width="320" alt="screen shot 2017-12-05 at 14 34 14" src="https://user-images.githubusercontent.com/11155743/33605129-6fc54224-d9c9-11e7-82bb-bd0f08721b4e.png">

**Comment by pgjones** [comment]
I agree with you and also really like the third logo, and the reasoning :). I'm working on a merge request with the logo, license (CC0 ok?) and attribution so we can start using it - which I'll add here (hopefully tomorrow).

On a practical note, Do you also have a svg version of the logo?

**Comment by koddr** [comment]
@pgjones great 👍 of cause I give you all formats of logo and guide style comments. CC0 is good.

I have another good idea. We are can create official GitHub organization (for example, `Quart-Python`) and transfer to here Quart core, design/logo guide style, some extensions and docs/site source for rapidly editing with community. All of this is the separate repositories, for best managing and issue reaction.

Similar way is already using by aiohttp/bottle projects and many more Python Web frameworks.

If you have not paid GitHub account for create organization — don’t worry, I have this stuff, create org and get you `boss` status.

**Comment by pgjones** [comment]
Ok, so I've opened this merge request https://gitlab.com/pgjones/quart/merge_requests/4 please can you take a look?

I think it is too early for an organisation, so far there is as yet too small a community working on Quart to make it worth while. Thanks for the suggestion and offer though :).

**Comment by koddr** [comment]
@pgjones I placed all logo's stuff to this repository: https://github.com/koddr/quart-logo

**Comment by pgjones** [comment]
Great I've merged and provided links to your repo. Thanks again.
