### ISSUE TITLE
reading from redis queue and sending data to webpage

### ISSUE THREAD

**Issue by juntiedt2** [pgjones/quart#10]
I got quart websocket example running on Python 3.6.4. Now I want to read data from a redis queue and send it to my webpage. 

I also will receive data from the web page and call functions within a class or if easier, put it into an outgoing redis queue. 

How can I best implement it in quart server?

I would very much appreciate your help in this matter

**Comment by pgjones** [comment]
I think splitting this into producing and consuming tasks makes sense, although I'm not sure. Does this work and make sense to you? I think it is the right idea.

```python
@copy_current_websocket_context
async def send():
    while True:
        data = await aioredis.receive()
        await websocket.send(data)

@copy_current_websocket_context
async def receive():
    while True:
        data = await websocket.receive()
        await aioredis.send(data)

@app.websocket('/')
async def index():
    sender = asyncio.ensure_future(send())
    receiver = asyncio.ensure_future(receive())
    gathered = asyncio.gather(sender, receiver)
    try:
        await gathered
    except CancelledError:  # Is raised when websocket connection closes
        gathered.cancel()
```

**Comment by juntiedt2** [comment]
Hi Phil,

 

thank you very much!

Yes, it looks very good. I found a similar example on the websockets page but did not know how to put it into Quart.

I tried to solve the problem with different namespaces – actually one websocket for sending and another for receiving, but yours looks much better.

 

Regards 

Hannes

 

Von: Phil Jones <notifications@github.com> 
Gesendet: Donnerstag, 1. März 2018 21:26
An: pgjones/quart <quart@noreply.github.com>
Cc: juntiedt2 <johannes@untiedt.net>; Author <author@noreply.github.com>
Betreff: Re: [pgjones/quart] reading from redis queue and sending data to webpage (#10)

 

I think splitting this into producing and consuming tasks makes sense, although I'm not sure. Does this work and make sense to you? I think it is the right idea.

@copy_current_websocket_context
async def send():
    while True:
        data = await aioredis.receive()
        await websocket.send(data)
 
@copy_current_websocket_context
async def receive():
    while True:
        data = await websocket.receive()
        await aioredis.send(data)
 
@app.websocket('/')
async def index():
    sender = asyncio.ensure_future(send())
    receiver = asyncio.ensure_future(receive())
    gathered = asyncio.gather(sender, receiver)
    try:
        await gathered
    except CancelledError:  # Is raised when websocket connection closes
        gathered.cancel()

**Comment by juntiedt2** [comment]
I tried  the following code together with your example Quart echo web page. 
Receiving data from redis queue and sending it to the webpage works ok. But receiving data from the webpage does not work. Why?

```
from quart import Quart, render_template, websocket
from RedisQueue import RedisQueue

app = Quart(__name__)
q_in = RedisQueue('ws_2')
q_out = RedisQueue('ws_3')

async def aioredis_receive():
    #return q_in.get()
    return q_in.get().decode("utf-8")
    
async def aioredis_send(data):
    q_out.put(data)    

@app.route('/')
async def index():
    return await render_template('index.html')

@app.websocket('/ws')
async def send():                        #send to Web-Page
    while True:
        data = await aioredis_receive()
        print("From redis queue: ", data)
        await websocket.send(data)

@app.websocket('/ws')
async def receive():                     #receive from Web-Page
    while True:
        data = await websocket.receive()
        print("From Web-Page: ", data)
        await aioredis_send(data)

@app.websocket('/ws')
async def ws():
    sender = asyncio.ensure_future(send())
    receiver = asyncio.ensure_future(receive())
    gathered = asyncio.gather(sender, receiver)
    try:
        await gathered
    except CancelledError:  # Is raised when websocket connection closes
        gathered.cancel()
        
if __name__ == '__main__':
    app.run(port=5000)

```

**Comment by pgjones** [comment]
I don't think redis queue is based on asyncio, so it will likely block the event loop. It may work to switch to use `asyncio.run_in_executor` but I think [asyncio-redis](https://github.com/jonathanslenders/asyncio-redis) is a better choice.

I'm also ensure what happens if you define a route many times (`@app.websocket('/ws')`), I don't think you need to and I think the last call will overwrite the previous ones.
