### ISSUE TITLE
Application Global Instance of aiohttp.ClientSession()

### ISSUE THREAD

**Issue by Yandawl** [pgjones/quart#100]
Hi there,

I am trying to create an instance of aiohttp that can be shared by either the whole Quart instance or even just within the scope of an object globally.

To give you a basic idea of what I am trying to do. An instance of the following class is created on application \_\_init\_\_ where I am creating an instance of Quart, which is passed into the object.

```python
import aiohttp
import asyncio

class ApiClient():

    def __init__(self, app): # app is an instance of Quart 
        self.token = app.config.get("TOKEN")
        self.api_base_uri = app.config.get("API_BASE_URI")

        loop = asyncio.get_event_loop()
        loop.run_until_complete(self.initialise_session(loop))

    async def initialise_session(self, loop):
        self.session = aiohttp.ClientSession(loop=loop)

    async def get_user(self, user_id):
        headers = { 'Authorization': self.token }
        url = f'{self.api_base_uri}/users/{user_id}'
        async with self.session.get(url, headers=headers, raise_for_status=True) as response:
            if response.status == 200:
                return await response.json()
```

However, I get the following error when I try to make get/ post requests using the instance of the session.

`RuntimeError Timeout context manager should be used inside a task`

I am a little perplexed as I would normally be able to do this in other applications but I have tried to create an instance of aiohttp.ClientSession within the async functions themselves right where I make the requests and this works.

What I would like to know is, is there an appropriate place that you'd recommend to store an instance of aiohttp.ClientSession that can be shared across my application and why my example strategy above isn't working in the context of Quart?

Many thanks!

**Comment by pgjones** [comment]
I typically make use of the before/after serving decorators and store on the app,
```python
@app.before_serving
async def startup():
    app.session = aiohttp.ClientSession()

@app.route("/")
async def index():
    app.session. ...
    # or current_app.session. ....
```

**Comment by Yandawl** [comment]
Thank you. I realised I was stupidly trying to access event loops before the app.run() so apologies for wasting your time.
