### ISSUE TITLE
Setting strict_slashes globally

### ISSUE THREAD

**Issue by grafolean** [pgjones/quart#101]
I am trying to convert an existing Flask app to Quart as an experiment. Most of the things went smoothly or I could find an equivalent approach in Quart, but I'm having trouble finding a way to tell Quart to ignore the trailing slashes. In Flask, this can be achieved like this:

```
app = Flask('my_app')
app.url_map.strict_slashes = False
```

I know I can set `strict_slashes` on routes, but this is repetitive and I would like to avoid it, if possible. Does Quart support something similar?

**Comment by pgjones** [comment]
I think `app.url_map.strict_slashes = False` should work, is it something you have tried?

**Comment by grafolean** [comment]
Yes, my app code is:
```
import quart as flask

app = flask.Quart(__name__, static_folder=None)
app.url_map.strict_slashes = False
```

I noticed this because I have a test that worked under Flask but is failing now. The test fails because it gets a response status code `404` (instead of `401` - missing credentials) when trailing slash is added:
```
        r = await app_client.get('/some/url')
        assert r.status_code == 401
        r = await app_client.get('/some/url/')
>       assert r.status_code == 401
E       assert 404 == 401
```

**Comment by pgjones** [comment]
Interesting, and is this with Quart >= 0.11? As 0.11 onwards uses the same url map as Flask does, so it is surprising to see this error.

**Comment by grafolean** [comment]
You nailed it, thank you very much!!! :)

I am using Python 3.6, which means that `pipenv install quart` found the latest version _compatible with Python 3.6_, which is `0.6.5`:
```
$ python --version
Python 3.6.6
$ pipenv update quart
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
✔ Success! 
...
All dependencies are now up-to-date!
$ pip freeze | grep -i quart
Quart==0.6.15
```

Sorry for the noise - it did seem a bit weird that this was not implemented, but... :) Just a suggestion, maybe a Python 3.6-compatible version (`0.6.16`) could be made that would warn users that they should upgrade Python?

Feel free to close this issue if you wish, and thank you very much for the fast help!

**Comment by pgjones** [comment]
Great, I wasn't looking forward to debugging this :).

At the moment I'd rather not release another 0.6.X and instead hope that people read [this](https://pgjones.gitlab.io/quart/discussion/python_versions.html).

**Comment by grafolean** [comment]
Sorry to bother you again, but the upgrade didn't help... :-/

The test fails in the same way, indicating that `strict_slashes` didn't change anything:
```
        import platform, quart
        assert platform.python_version() == '3.8.2'
        assert quart.__version__ == '0.11.3'

        r = await app_client.get('/some/url')
        assert r.status_code == 401
        r = await app_client.get('/some/url/')
>       assert r.status_code == 401
E       assert 404 == 401
E        +  where 404 = Response(404).status_code
```

API also behaves the same way:
```
$ curl -i http://127.0.0.1:5000/api/status/info | head -n 1
HTTP/1.1 200 
$ curl -i http://127.0.0.1:5000/api/status/info/ | head -n 1
HTTP/1.1 404 
```

The code is:
```
import quart as flask
app = flask.Quart(__name__, static_folder=None)
app.url_map.strict_slashes = False
```

The versions are:
```
$ python --version
Python 3.8.2
$ pip --version
pip 20.0.2 from .../lib/python3.8/site-packages/pip (python 3.8)
$ pip freeze | grep -i quart
Quart==0.11.3
```

I did however find a workaround using redirects:
```
import quart as flask

@app.before_request
def clear_trailing_slash():
    path = flask.request.path
    if len(path) > 1 and path[-1] == '/':
        return flask.redirect(path[:-1])
```

Also, I tried looking at the Quart code but couldn't find the cause by manual inspection - to me it looks like `url_map` is a subclass of `werkzeug.routing.Map` and I couldn't find any error in passing the `strict_slashes` parameter. To me it looks like this could be a bug (or at least a breaking change) in werkzeug. I found a few issues connected to this but nothing exacly like this... If you have any ideas on how to best tackle this, I'd appreciate it...

**Comment by grafolean** [comment]
@pgjones Do you have any idea how to solve this?

**Comment by pgjones** [comment]
I think this is a bug in Quart, which is fixed in 3f593258ad0f0b3a5e552ca0afb573f3aedfe827. Could you try it out?

**Comment by grafolean** [comment]
Sure, happy to - unfortunately the fix didn't help (both the test and manual testing show the same bug).

If it helps, I have created a very small repo that reproduces the bug: https://github.com/grafolean/quart-strict-slashes. The latest commit there is using https://github.com/pgjones/quart/commit/3f593258ad0f0b3a5e552ca0afb573f3aedfe827, but there is no difference in behavior from Quart master afaict.

**Comment by pgjones** [comment]
Ah, I think 37d539de01532c8771e997e306a5dd3b79d71470 will solve it.

**Comment by grafolean** [comment]
Perfect - yes, it does. Both the test repository and the app now work correctly. :)

Thank you for solving this!
