### ISSUE TITLE
Quart hello world eats 25-30% of my CPU

### ISSUE THREAD

**Issue by tuxedo78** [pgjones/quart#104]
Hi,
When running the simple Quart hello world example, I see 25-30% of CPU taken on my PI0 or PI-3B+.
I'm using Python 3.7.3
I was not expecting such high load when nothing is really happening.

**Comment by pgjones** [comment]
I would guess you are using `app.run()` which runs a auto reloader that works by continually checking the files for changes. The reloader has become more efficient in Hypercorn >=0.10.0. Alternatively if you run your app without the reloader e.g. `hypercorn module:app` it should get better.

Please let me know if this is it.

**Comment by tuxedo78** [comment]
Indeed I had hypercorn 0.9.5... but after upgrading to 0.10.1 the CPU usage went down to slightly less than 10% (even when running with python3 hello-world.py). Is it the CPU load that you would expect as well or is there any other trick to optimize again? :)

**Comment by pgjones** [comment]
Is this CPU usage using `app.run` or `hypercorn module:app`?

**Comment by tuxedo78** [comment]
Well I don't observe a striking difference between both methods... do you observe something really visible? Is there any way to avoid this reloader mechanism at all (any flag to app.run for this)?

What made a BIG difference was to upgrade from Hypercorn 0.9.5 to 0.10.1. Thanks for the good tip :)

**Comment by pgjones** [comment]
There is an [app.run flag](https://github.com/pgjones/quart/blob/master/src/quart/app.py#L1572) called `use_reloader`. 

I've not considered the CPU usage whilst idling before, something I'll need to look into.

**Comment by tuxedo78** [comment]
Indeed it drastically reduces the CPU load :)
What's the point of having **use_reloader** being **True** by default?

**Comment by pgjones** [comment]
`app.run` is meant for development and not production, hence the auto reloading on changes being very helpful.

There is something strange going on here though, as the `hypercorn module:app` usage has the reloader off. Have you protected the `app.run` in a main guard?
```python
if __name__ == "__main__":
    app.run()
```

**Comment by tuxedo78** [comment]
I simply run the **hello world** code from [here](https://pgjones.gitlab.io/quart/tutorials/quickstart.html)
