### ISSUE TITLE
quart_session

### ISSUE THREAD

**Issue by Jay484** [pgjones/quart#105]
in quart_session/__intit__.py, calling session_interface = NullSessionInterface() when config["SESSION_TYPE"] doesn't satisfy any if conition. But in quart_session/sessions.py declaration is something like : class NullSessionInterface(SessionInterface). It throws following error:
 line 133, in _get_interface
    session_interface = NullSessionInterface()
TypeError: __init__() missing 1 required positional argument: 'key_prefix'

**Comment by pgjones** [comment]
Did you solve this?

**Comment by Jay484** [comment]
Not really..I was checking if same error occurs in Flask. But Flask doesn't throw such error. I can send you code snippet that throws error, If you want me to

**Comment by Jay484** [comment]
from quart import Quart
from quart_session import Session

app= Quart(__name__)
app.config["SESSION_TYPE"]='mongo'   #'redis' works fine at this instance
Session(app)
app.run()

**Comment by pgjones** [comment]
It doesn't look like Quart-Session [supports](https://github.com/xmrdsc/quart-session#features) mongo - could this be the problem?

**Comment by Jay484** [comment]
even if you remove mongo, just dont specify session type , It still throws error

from quart import Quart
from quart_session import Session

app= Quart(name)
Session(app)
app.run()

**Comment by pgjones** [comment]
Ah, I think it is this [issue](https://github.com/xmrdsc/quart-session/issues/1).

Also note that all the examples explicitly set `app.config['SESSION_TYPE']`.

**Comment by xmrdsc** [comment]
@Jay484 unfortunately at this time `quart-session` does not support MongoDB has a session back-end, biggest reason being that I never used MongoDB and it seems like Redis or Memcached is a better fit. However, `MongoDBSessionInterface` is on the TODO as per `README.md` so perhaps someone could PR that sometime :-)

In addition I fixed the NullSessionInterface.

**Comment by Jay484** [comment]
okay got it
