### ISSUE TITLE
send data to websocket from http route

### ISSUE THREAD

**Issue by beqabeqa473** [pgjones/quart#106]
hello.

is it possible to send data to websocket context from http route?

i didn't understand if it is possible to share websocket context to another functions.

i read about copy_current_websocket_context, but it is for other tasks as i understand, but i need to send something from http route.

is it possible to do that?

thanks.

**Comment by pgjones** [comment]
It is not possible to use the websocket context in http routes. This is because the client has to make a websocket connection rather than a http request.

**Comment by beqabeqa473** [comment]
i already have active connection from a single client.
for this specific project, i have only one client connection, so maybe
it is possible to get active connection object and send data there?

On 7/7/20, Phil Jones <notifications@github.com> wrote:
> It is not possible to use the websocket context in http routes. This is
> because the client has to make a websocket connection rather than a http
> request.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pgjones/quart/issues/106#issuecomment-655067775


-- 
with best regards beqa

**Comment by xmrdsc** [comment]
See https://pgjones.gitlab.io/quart/tutorials/websocket_tutorial.html#broadcasting

You'd call `broadcast(...)` from the HTTP route.
