### ISSUE TITLE
Avoiding Timeouts on Heroku

### ISSUE THREAD

**Issue by MrUltimate** [pgjones/quart#107]
Hello! Thanks for all your work on Quart and the community.

I'm currently building an API that scrapes news and runs sentiment analysis on it. While on my local machine, in most cases the request is performed in under 30secs, on Heroku more often than not, my requests are being timed out. I was wondering what's the best way to avoid timeouts?

Here's my app.py: https://github.com/MrUltimate/good-vibes-api/blob/master/app.py

Would love some help/guidance on this. Thanks!

**Comment by pgjones** [comment]
See https://gitlab.com/pgjones/quart/-/issues/346

**Comment by michaeljarizala** [comment]
> See https://gitlab.com/pgjones/quart/-/issues/346

I have read this but I'm quite confused, do we still need to `SSE` on simple `GET` requests?

I have a GET endpoint `http://quart-h2-sample-1.herokuapp.com/?server_push=false` which serves a simple html page displaying a very simple database content. Everything works great on my local machine. But on Heroku the build succeeds, but when I visit the app on the browser I always get Heroku's `H13` error or an equivalent `HTTP 503 "Content closed without response"` error.

Btw, my Heroku `Procfile`:
`web: hypercorn --certfile cert.pem --keyfile key.pem --bind 0.0.0.0:$PORT manage`

And here's a sample Heroku log:

> 2020-11-21T17:56:40.812320+00:00 heroku[web.1]: State changed from starting to up
2020-11-21T17:56:41.000000+00:00 app[api]: Build succeeded
2020-11-21T17:57:58.781081+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/?server_push=false" host=quart-h2-sample-1.herokuapp.com request_id=21af2130-cd94-4dcf-9cfd-a7d4d6be6102 fwd="49.145.197.127" dyno=web.1 connect=1ms service=2ms status=503 bytes=0 protocol=https

Do you have any hint on what may be wrong or missing here?

**Comment by michaeljarizala** [comment]
> > See https://gitlab.com/pgjones/quart/-/issues/346
> 
> I have read this but I'm quite confused, do we still need to `SSE` on simple `GET` requests?
> 
> I have a GET endpoint `http://quart-h2-sample-1.herokuapp.com/?server_push=false` which serves a simple html page displaying a very simple database content. Everything works great on my local machine. But on Heroku the build succeeds, but when I visit the app on the browser I always get Heroku's `H13` error or an equivalent `HTTP 503 "Content closed without response"` error.
> 
> Btw, my Heroku `Procfile`:
> `web: hypercorn --certfile cert.pem --keyfile key.pem --bind 0.0.0.0:$PORT manage`
> 
> And here's a sample Heroku log:
> 
> > 2020-11-21T17:56:40.812320+00:00 heroku[web.1]: State changed from starting to up
> > 2020-11-21T17:56:41.000000+00:00 app[api]: Build succeeded
> > 2020-11-21T17:57:58.781081+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/?server_push=false" host=quart-h2-sample-1.herokuapp.com request_id=21af2130-cd94-4dcf-9cfd-a7d4d6be6102 fwd="49.145.197.127" dyno=web.1 connect=1ms service=2ms status=503 bytes=0 protocol=https
> 
> Do you have any hint on what may be wrong or missing here?

By the way, I am ONLY experiencing this when I configure Hypercorn to use `SSL`. But when I remove `--certfile` and `--keyfile` (which will make the server NOT run on SSL), the page gets served just well using HTTP.

Hope anyone could help on this one? Thanks!

**Comment by pgjones** [comment]
Heroku does not support SSL between the Heroku router and the app, therefore it will not understand the HTTPS response and give the error.
