### ISSUE TITLE
Can't export factory function

### ISSUE THREAD

**Issue by itsDrac** [pgjones/quart#108]
Hi, So my directory looks something like 
```Bash
app/
|   __init__.py
```
and `__init__py` looks like
```
from quart import Quart

def create_app():
    app = Quart(__name__)

    return app
```

now the problem is when i export create_app()  **_with parentheses_**
```Bash
export QUART_APP=app:create_app()
```
Bash throws an error saying
```Bash
bash: syntax error near unexpected token `('
```
and when i export create_app  **_without parentheses_**
```Bash
export QUART_APP=app:create_app
```
quart throws an error saying
```Bash
Error: Could not locate a Quart application
```
So, How do i export an application factory app?

**Comment by pgjones** [comment]
`export QUART_APP="app:create_app()"` will do the trick (note the `"`).

**Comment by itsDrac** [comment]
> `export QUART_APP="app:create_app()"` will do the trick (note the `"`).

I Should have tried that 😅
Thanks! that works
