### ISSUE TITLE
Automatic reloading in debug mode

### ISSUE THREAD

**Issue by DoHe** [pgjones/quart#11]
As documented [here](http://flask.pocoo.org/docs/0.12/quickstart/#debug-mode) flask provides automatic reloading on code change when the debug mode is enabled.
This doesn't seem to be the case for quart (I tried the `QUART_DEBUG` (cf [here](https://github.com/pgjones/quart/blob/master/quart/helpers.py#L14)) environment variable, as well as manually setting the app config).
It is a really helpful feature during development and it would be great if quart could offer it too.

**Comment by pgjones** [comment]
I've tried to add this, can you try the latest master? (`quart run` must be used). See 648de84957c2dc83070a04f4769d937b19587c3f

**Comment by DoHe** [comment]
Thanks, it's working like a charm. Sorry for not spotting this.

**Comment by pgjones** [comment]
Thanks for testing. Also I this added after you asked :p.

**Comment by DoHe** [comment]
I'm reopening this, as it seems that running in debug mode on current master swallows exceptions. I could imagine that maybe it is somehow tied to the usage of `execv`? Maybe it's also unrelated to this commit, if so feel free to close this again.

**Comment by pgjones** [comment]
I just tried and I see exceptions on reload (prevents the reload) and exceptions within a route (500 response and exception logged). Did you mean some other type of exception? Could you reply with some code I can to use to reproduce?

**Comment by DoHe** [comment]
This already is enough for me to reproduce:
```python
from quart import Quart, render_template

app = Quart(__name__)


@app.route("/")
def index():
    raise Exception('ouch')
    return render_template('index.html')

if __name__ == '__main__':
    app.run()
```
The exception is returned in the response:
![grafik](https://user-images.githubusercontent.com/11160629/37556889-a8a2efc8-29fc-11e8-9e08-ad1cab26b236.png)
but is not logged in the command line:
> Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2018-03-17 15:57:29,770] 127.0.0.1 GET / h11 500 22408 80989

Running the same code without debug logs the exception as expected:
> [2018-03-17 16:04:01,130] ERROR in app: Exception on request GET /
Traceback (most recent call last):
[...]
  File "error.py", line 8, in index
    raise Exception('ouch')
Exception: ouch


I hope that helps?

**Comment by pgjones** [comment]
Thanks, I fixed this in 022b90ac7395b516771a7d77595033b5c56c427a after breaking it in b3681d33fc69c0499038a1f58a8576da26ba3247

**Comment by DoHe** [comment]
Awesome, now everything is really working like a charm.

**Comment by RayyanNafees** [comment]
It isn't reloading if the file with error was saved
