### ISSUE TITLE
Problem with send_file

### ISSUE THREAD

**Issue by Danstiv** [pgjones/quart#112]
Hi.
I have two similar scripts: 
First - flask realization
```
import flask
app = flask.Flask(__name__)
@app.route('/')
def index():
	return flask.send_file('file.dat', conditional=True)
app.run()
```
And second - quart realization
```
import quart
app = quart.Quart(__name__)
@app.route('/')
async def index():
	return await quart.send_file('file.dat', conditional=True)
app.run()
```
When i tryed download file from flask script, i saw a final size of the file.
But quart don't sent final size of the file.
And when i looked at the headers, in response from flask server i saw Content-Length header, but quart don't sends this header.
Also, downloading from flask server was successfully completed, but quart resets the downloading in about a minute, and file does not load completely.

**Comment by pgjones** [comment]
> But quart don't sent final size of the file.

Do you mean the Content-Length? If so Quart was streaming files (chunked transfer encoding), which I've changed in 5a39178cf616841c79b1f8fdf620694f70df8b72 to match Flask and set a content length. This should work though.

I'm not sure why the downloading fails with Quart though, everything works correctly when I try. Could you provide more information about how it fails (what client, any error messages etc)?
