### ISSUE TITLE
'Quart' object has no attribute 'asgi_app'

### ISSUE THREAD

**Issue by vashchukmaksim** [pgjones/quart#115]
I have a Quart app that works perfectly fine. Now I'm trying to add `SentryAsgiMiddleware` the way it is described in docs
https://pgjones.gitlab.io/quart/how_to_guides/middleware.html:

```
app = Quart(__name__)
app.config.from_object(config_class)
app.asgi_app = SentryAsgiMiddleware(app.asgi_app)
```

but I receive the following error:

```
AttributeError: 'Quart' object has no attribute 'asgi_app'
```

which is weird.

That looks like a bug but probably I do something wrong.

Python 3.6
Quart 0.14.0
SentrySDK 0.19.4

**Comment by vashchukmaksim** [comment]
Sorry, my remote machine for some reason can't find the latest version so it uses the last it can find `Quart==0.6.15`. Interesting... Hope that the error is because of the version number then

**Comment by pgjones** [comment]
I think your remote machine is running Python 3.6, if you install 3.7 or greater it will find the latest version.
