### ISSUE TITLE
Number gets reduced

### ISSUE THREAD

**Issue by shahprog** [pgjones/quart#117]
Today I found a very strange thing.

In on of my route I am rendering a template with a number which is `700374484955299900`
And when I print that in a view it prints correctly but when On that teamplate I did post request with the same number to a different route and print the number by fetching it like 

```py
datas = json.loads(await request.data)
print(datas['the_number'])
```
 Number gets reduced and becomes `700374484955299800` Here 100 got removed from the number.

And I have no clue why.

**Comment by pgjones** [comment]
This is most likely due to how you use the number in Javascript, as Javascript numbers lose precision ([top google result](https://www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues)).
