### ISSUE TITLE
Flask-socket-io with quart server?

### ISSUE THREAD

**Issue by juntiedt2** [pgjones/quart#12]
is it possible to have something like Flask-socket-io in quart? Would make migration to quart easier.

**Comment by pgjones** [comment]
I'm not sure it belongs in Quart, but it should be very possible to write an extension that does this or maybe add Quart to [Engine.io](https://github.com/miguelgrinberg/python-engineio) and build the extension on it.

**Comment by juntiedt2** [comment]
Hi Phil,

 

thank you very much for your quick response!

I agree with you, that socket.io does not belong to quart, but it would be a very good add-on.

I have Quart running , including redis read and write and I like the performance. With Quart I am handling events using websocket path, which is ok if you have only a few event types. I my case , I have about 30 event types and then socket.io would be very helpful.

I have looked into Engine.io. That is exactly what I am looking for. Would be nice if it works with quart.

 

Regards

Hannes

 

Von: Phil Jones <notifications@github.com> 
Gesendet: Donnerstag, 15. März 2018 21:42
An: pgjones/quart <quart@noreply.github.com>
Cc: juntiedt2 <johannes@untiedt.net>; Author <author@noreply.github.com>
Betreff: Re: [pgjones/quart] Flask-socket-io with quart server? (#12)

 

I'm not sure it belongs in Quart, but it should be very possible to write an extension that does this or maybe add Quart to Engine.io <https://github.com/miguelgrinberg/python-engineio>  and build the extension on it.
