### ISSUE TITLE
No websocket.close?

### ISSUE THREAD

**Issue by shivna-2020** [pgjones/quart#122]
```
@app.websocket('/test')
async def test():
    queue = some_function_that_returns_queue()
    await websocket.accept()
    while True:
        data = await queue.get()
        if data == None:
                await websocket.close(1000)
                return 
        else:
            await websocket.send(data)
```

There is no websocket.close function available as listed in the documentation.
https://pgjones.gitlab.io/quart/how_to_guides/websockets.html

**Comment by pgjones** [comment]
Sadly, I've not released this yet - you can either use the master branch or wait for 0.15.0.

**Comment by SylteA** [comment]
> Sadly, I've not released this yet - you can either use the master branch or wait for 0.15.0.

Any estimate on when 0.15.0 will be released?

**Comment by pgjones** [comment]
Early May is my aim, after Werkzeug 2.0 has been released.

**Comment by SylteA** [comment]
What about a prerelease with Websocket.close included?
