### ISSUE TITLE
Basic auth implementation

### ISSUE THREAD

**Issue by FranciscoSilveira** [pgjones/quart#123]
Hello,

I've been trying to implement a basic auth decorator in Quart, both based on [your suggestion on SO](https://stackoverflow.com/questions/65147521/basic-auth-for-quart-python) and the documentation of how basic auth works, so that it will actually request basic auth credentials in the browser. What I have is similar to your own solution, with a few relevant differences:

- it requests basic auth credentials if absent/wrong instead of just raising a 401.
- the decorator expects a response body for wrong credentials and optionally a realm for the credentials request.
- the basic_auth decoration must happen after any app.route decoration, while in your example the order doesn't matter the other way around. I'm not sure why.

If this something you'd be interested in adding as a decorator in quart itself, or as a snippet in the documentation, this is what I came up with:

```python
from secrets import compare_digest
from typing import *

from quart import Quart, abort, current_app, request, Response
from quart.wrappers.response import ResponseBody

app = Quart(__name__)
app.config["BASIC_AUTH_CREDENTIALS"] = {
    "username": "password",
}


def auth_required(
        rejection_response: Union[ResponseBody, AnyStr, Iterable],
        realm=""
    ):
    def auth_wrapper(func):
        async def auth_inner_wrapper(*args, **kwargs):
            auth = request.authorization
            if (
                auth is not None and
                auth.type == "basic" and
                compare_digest(auth.password, current_app.config.get("BASIC_AUTH_CREDENTIALS", {}).get(auth.username, ""))
            ):
                return await func(*args, **kwargs)
            else:
                abort(Response(
                    rejection_response,
                    status=401,
                    headers={
                        "WWW-Authenticate": "Basic realm=\""+realm+"\""
                    }
                ))
        return auth_inner_wrapper

    return auth_wrapper


# Usage

@app.route("/")
@auth_required("Invalid credentials", realm="Public access")
async def index():
    return "Proper credentials"
```

**Comment by FranciscoSilveira** [comment]
Upon more use, it seems that this fails with a an AssertionError that seems to indicate that I'm re-defining 2 routes to the same endpoint function:

`AssertionError: Handler is overwriting existing for endpoint auth_inner_wrapper`

This seems to be because the decorator for basic auth needs to be in the line below the app.route decoration - so it is called before - and the decoration chain inside means that the function returned by the basic auth decorator always has the same name: "auth_inner_wrapper". [A better example here](https://stackoverflow.com/questions/17256602/assertionerror-view-function-mapping-is-overwriting-an-existing-endpoint-functi). I think changing the decorator function's name to the decorated one's name is a valid solution, but functools.wraps might be cleaner:

```
from functools import wraps
from secrets import compare_digest
from typing import *

from quart import abort, current_app, request, Response
from quart.wrappers.response import ResponseBody


def auth_required(
        rejection_response: Union[ResponseBody, AnyStr, Iterable],
        realm=""
    ):
    def auth_wrapper(func):
        @wraps(func)
        async def auth_inner_wrapper(*args, **kwargs):
            auth = request.authorization
            if (
                auth is not None and
                auth.type == "basic" and
                compare_digest(auth.password, current_app.config.get("BASIC_AUTH_CREDENTIALS", {}).get(auth.username, ""))
            ):
                return await func(*args, **kwargs)
            else:
                abort(Response(
                    rejection_response,
                    status=401,
                    headers={
                        "WWW-Authenticate": "Basic realm=\""+realm+"\""
                    }
                ))
        return auth_inner_wrapper

    return auth_wrapper
...

**Comment by pgjones** [comment]
Thanks! I think this is best as an addition to Quart-Auth's docs - I'm open to a convincing argument that it should be in the code, but so far I think it's usage will be too specific to the user.

**Comment by FranciscoSilveira** [comment]
I kept it out of quart-auth since the goal was to provide cookie authentication, but if you'd be open to a broader scope of a generic auth module, I think it makes more sense there. Do you want me to move the issue there?

I noticed that if you're using websockets, the basic auth will be present in the `websocket` variable instead of the `request`. If we're in a HTTP context and we try to get anything from websocket it will throw an error and vice-versa for being in a websocket context. So I think it would be reasonable to try and get it first from `request`, if that fails get it from `websocket`.

**Comment by pgjones** [comment]
I've added this as a decorator to [Quart-Auth](https://gitlab.com/pgjones/quart-auth/-/commit/0b7308cfe65a7f0f38fcc3e6411e56d3b8b596e7)
