### ISSUE TITLE
Websocket guidance needed

### ISSUE THREAD

**Issue by davegravy** [pgjones/quart#13]
I've got the echo websocket tutorial working fine with a javascript client, but I'm lost as to how to go forward

(Other than learning Twisted I'm pretty new to python web libraries and async programming, so I wouldn't be surprised if this is just a lack of knowledge on my part rather than lack of Quart documentation)

I want my browser client to provide some parameters to the server initially, to identify what types of data that client is subscribing to, and trigger the Quart application to begin fetching and caching that data from another server (paginated REST API). As that data becomes cached locally I want to forward it via the websocket to the client... and really to any other websocket clients subscribed for the same kind of data.

Any guidance via examples or references to learning materials would be appreciated!

**Comment by pgjones** [comment]
As you describe what you'd like to do, I think you could stream the response, for example have you looked at [Server Sent Events](https://pgjones.gitlab.io/quart/broadcast_tutorial.html)? I think a websocket would be better if you wanted continuous two way communication between the client and server. 
Have you also looked at the [aiohttp client](https://docs.aiohttp.org/en/stable/#getting-started) example, as it is the best way to fetch the data. 

This is a rough guess as to what you want, I've not tried it but the basic idea is hopefully clear,
```python
import aiohttp
from quart_tutorial import ServerSentEvent  # Pseudo code
from quart import request

@app.route('/')
async def index():
    param = request.args.get('param', 'default_value')

    async def send_results_as_fetched():
        async with aiohttp.ClientSession() as session:
            for url in urls_to_fetch(param):
                async with session.get(url) as response:
                    data = await response.json()
                    yield ServerSentEvent(data)

    return send_results_as_fetched(), {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Transfer-Encoding': 'chunked',
    }
```

```javascript
var es = new EventSource('/');
es.onmessage = function (event) {
  ....
```

**Comment by pgjones** [comment]
Does this help https://medium.com/@pgjones/websockets-in-quart-f2067788d1ee ?

**Comment by davegravy** [comment]
Very much so, thanks for that!

**Comment by trashcluster** [comment]
Hi, i don't know if i should open a new issue or just continue this thread :D  
I'm completely new to WebSockets and Flask and Quart and Async python programming hence my extreme headache after 3 days of non stop trying to figure on how to send websocket data from a trigger.  
I have an endpoint with a websocket client connecting to a Quart server and it works nicely with websockets functions. What i want is being able to send websocket messages when i call an http url.  
I the end i want to control that websocket client device by doing api calls on a quart app.  
As deep as i read the documentation i can't make sens of how to do this. Any tips ?

**Comment by pgjones** [comment]
@trashcluster It isn't clear to me what you are asking, nor what you want to achieve. If by websocket message you mean JSON encoded data, then you can send that either via a WebSocket message or a request body.

Probably be better to continue the conversation [here](https://gitter.im/python-quart/lobby).
