### ISSUE TITLE
Socket streaming is throwing a timeout when I try to connect via Postman (w/ and w/o socket.io) 

### ISSUE THREAD

**Issue by OhBehive** [pgjones/quart#135]
How exactly am I meant to connect to websocket / streamed endpoint? I'm either getting a timeout, a 400 or a 302 error when running on a cloud run instance 

I've tried these endpoints

wss:/{base_url}/api/v1/ws
ws:/{base_url}/api/v1/ws
wss:/{base_url}:8080/api/v1/ws
ws:/{base_url}:8080/api/v1/ws

code is here:

```
@app.websocket('/api/v1/ws')
async def ws_v1():
    while True:
        data = await websocket.receive()
        await websocket.send(f"echo {data}")


```
i've even tried streamed response here: but this also either times out or throws a 400.

```
@app.route('/ws')
async def ws():
    @helpers.stream_with_context
    async def async_generator():
        time = datetime.utcnow()
        yield str(time).encode()
    return async_generator(), 200, {'X-Something': 'value'}

@app.route("/ws")
async def http_ws():
    return "A HTTP request"

```

**Comment by pgjones** [comment]
See https://gitlab.com/pgjones/quart/-/issues/443
