### ISSUE TITLE
How to make a quart chat room?

### ISSUE THREAD

**Issue by joaopedrolourencoaffonso** [pgjones/quart#136]
I am trying to make a quart application using multiple websockets at the same time:

`
<script type="text/javascript">
         let socket = new WebSocket('ws://localhost:5000/mensagens/{{ dialog_id }}');
         socket.onmessage = function(event) {
                  var messages_dom = document.getElementsByTagName('ul')[0];
                  var message_dom = document.createElement('li');
                  var cotent_dom = document.createTextNode(event.data);
                  message_dom.appendChild(cotent_dom);
                  messages_dom.appendChild(message_dom);
         };
</script>

<script>
         let ws = new WebSocket('ws://localhost:5000/printar/12');
         function myFunction() {
                  var x = document.getElementById("myText").value;
                  ws.send(x);
                  document.getElementById("demo").innerHTML = x;
	};
</script>
`

And this is the server side:

`
#Quart
from quart import Quart, render_template, url_for, websocket, redirect, request

#asyncio
import asyncio

app = Quart(__name__)

...
#websocket da conversa individual
@app.websocket('/mensagens/<dialog_id>')
async def mensagens(dialog_id):
         print("123");
         try:
                  output = await ".....function that updates from the SQLite database....";
                  await websocket.send(f"{output}");
         
         await asyncio.sleep(1);

         except Exception as e:
                  print("-------");
                  print(e);

#websocket de enviar mensagens
@app.websocket('/printar/<dialog_id>')
async def printar(dialog_id):
         print("aqui");
         try:         
                  while True:
                           print(dialog_id);
                           data = await websocket.receive();
                           print(data + "\n=====");

         except Exception as e:
                  print(e);

if __name__ == "__main__":
    try:
        app.run();

    except KeyboardInterrupt:
        print("=====\nAdeus!\n=====");

    except Exception as e:
        print(e);
`

However, for some  reason, the **second** websocket only begin to run after the first websocket receives an update from "mensagens". I really don't understand what and why is happening. 

Is there an example of a chat server made with Quart that I could look at?

**Comment by joaopedrolourencoaffonso** [comment]
For some reason github couldn't understand my code, but, I manage to post the question correctly on github
https://stackoverflow.com/questions/69954196/quart-chat-server-example

**Comment by joaopedrolourencoaffonso** [comment]
I ended up answering my own question. For anyone interested, here is the example:
https://stackoverflow.com/questions/69954196/quart-chat-server-example/69954419#69954419

**Comment by pgjones** [comment]
There is also this [article](https://medium.com/@pgjones/websockets-in-quart-f2067788d1ee) which is a little outdated now, but hopefully still useful.

**Comment by joaopedrolourencoaffonso** [comment]
Thanks!
