### ISSUE TITLE
Python 3.6.0 is not compatible

### ISSUE THREAD

**Issue by lalvarezguillen** [pgjones/quart#15]
Hi.

You're importing typing.AsyncGenerator [here](https://github.com/pgjones/quart/blob/master/quart/wrappers/response.py#L7), and the docs claim python 3.6 compatibility, but AsyncGenerator doesn't seem to be included in Python 3.6.0.

I failed to find the changelogs, but I tested with Python images available in Dockerhub, and AsyncGenerator doesn't appear until 3.6.1.

I wonder if this is worth pointing out somewhere in the docs.

[This](https://github.com/python/typing/issues/530) is a relevant issue from the python/typing project.

Keep it up!

**Comment by pgjones** [comment]
Thanks for finding this :). I've pushed an update to warn people on installation 5e8c9416f7278df8232f1bdb2d4b490abd5e01fd.
