### ISSUE TITLE
[Question] Roadmap to major version of Quart (1.x.x)

### ISSUE THREAD

**Issue by koddr** [pgjones/quart#2]
Hello, @pgjones, it's me again.

Today's question is roadmap to major version of Quart `1.x.x`. Could you please give to community some plan or wishes. What does Quart framework want now and what do you want to implement in the future?

Thanks.

**Comment by pgjones** [comment]
I don't have a roadmap to `1.x.x` as yet, but the roadmap and plans for the next release are tracked on [gitlab](https://gitlab.com/pgjones/quart/issues) and I've been adding issues I think need completing for the next release.

More than welcome to hear suggestions.

**Comment by jykae** [comment]
I really like the idea of being Flask compatible, this would ease the switch from existing Flask applications. I wish good future for Quart framework 👍

**Comment by pgjones** [comment]
@jykae are there any incompatibilities you know of at the moment?

**Comment by jykae** [comment]
@pgjones At the time of writing the previous comment, I just found this project while searching about Flask, async, as well as asyncio. Have not yet tried out and cannot say anything about incompatibilities.

**Comment by koddr** [comment]
@jykae also, you may listen about Quart and it author & philosophy at 147 episode of Talk Python to Me podcast ;)

Btw, it’s me writing many twits to Michael Kennedy about Quart and Philip Jones for gets this topic to episode :)

**Comment by pgjones** [comment]
@koddr thanks, it was good fun.

**Comment by pgjones** [comment]
@koddr (and others) I've created https://quart.zulipchat.com/ on this suggestion https://gitlab.com/pgjones/quart/issues/88 if you want to discuss the roadmap in a chat like setting.
