### ISSUE TITLE
Catch-All URL

### ISSUE THREAD

**Issue by Madhu1512** [pgjones/quart#21]
I am trying to create  catch-all-url route similar to flask, but the route is not working in quart.

Flask:

`from flask import Flask, request`
 `app = Flask(__name__)`

`@app.route('/', defaults={'path': ''})`
`@app.route('/<path:path>')`
`def index(path):`
    `return 'Hello World'`

Quart:

`from quart import Quart, request`
`app = Quart(__name__)`

`@app.route('/', defaults={'path': ''})`
`@app.route('/<path:path>')`
`async def index(path):`
    `return 'Hello World'`

What is the best way to create catch all route in quart?

**Comment by pgjones** [comment]
Your suggestion is the best, however I made a simple mistake that is now fixed in master 756e52d8896a8c63cb865ae6d375e61b5a09982d. If you could try master and confirm?

**Comment by Madhu1512** [comment]
working as expected, Thanks for fixing this. When can i expect a new version with this fix?

**Comment by pgjones** [comment]
I'm not sure yet, I need to scope out what is required. Can you work of, off this commit or master?
