### ISSUE TITLE
Adding a way to run a startup / cleanup routine

### ISSUE THREAD

**Issue by vivescere** [pgjones/quart#23]
Hi!

I've been trying to use [aiomysql](https://github.com/aio-libs/aiomysql) with Quart. Opening a new connection for each request works fine, but isn't quite resource efficient. So I've decided to use a pool.

To create / destroy the pool correctly, I need access to the loop. I can use the signal `before_first_request` to create the pool. However, I can't seem to find a way of running a method before the loop is closed.

So, I sub-classed the custom worker:

```python
class CustomWorker(GunicornUVLoopWorker):

    def run(self) -> None:
        create_server = asyncio.ensure_future(self._run(), loop=self.loop)

        try:
            self.loop.run_until_complete(create_server)
            self.loop.run_until_complete(self._check_alive())
        finally:
            self.loop.run_until_complete(self.loop.shutdown_asyncgens())
            self.loop.run_until_complete(self._cleanup())
            self.loop.close()

    async def _cleanup(self):
        if not hasattr(app, 'pool'):
            return

        pool.close()
        await pool.wait_closed()
        del app.pool
```

I was wondering if there was a cleaner way to do this. Especially because now, I can't run the built in server, and have to add a special configuration to `pytest` to make it run:

```python
@pytest.yield_fixture(autouse=True)
async def run_around_tests():
    # Before each test
    yield
    # After each test
```

Thanks!

**Comment by pgjones** [comment]
Hello, a very similar question was asked [here](https://gitlab.com/pgjones/quart/issues/102) which has in its answer a solution. I'm now starting to strongly lean towards the before/after serving solution, do you think it would solve your issues?

**Comment by vivescere** [comment]
Sorry, I didn't think to check the issues on gitlab (only on github). The implemented solution is similar to mine.

I do think that implementing a before/after serving solution would be really useful, and would make integrating other libraries easier.

It should be possible for both gunicorn, and the builtin server, but I'm not sure you'd be able to ensure that they are executed with any other server.

**Comment by pgjones** [comment]
@vivescere I think [this](https://pgjones.gitlab.io/quart/startup_cleanup.html) is the functionality that you want. It will be in the next release.

**Comment by vivescere** [comment]
This is exactly what I was looking for! Thank you for adding it.
