### ISSUE TITLE
How to consume JWT token?

### ISSUE THREAD

**Issue by mthota15** [pgjones/quart#26]
Looking for some guidance or example on how to consume JWT token with Quart? is there a extension that works with quart?

**Comment by pgjones** [comment]
It looks like [Flask-JWT-Simple](https://github.com/vimalloc/flask-jwt-simple) works with the [flask patching](https://pgjones.gitlab.io/quart/flask_extensions.html) system in Quart. There is no Quart specific extension as far as I know though.

**Comment by mthota15** [comment]
is there a concept like middlewares in quart, where we can write custom middleware, something similar to code mentioned in the post: https://steelkiwi.com/blog/jwt-authorization-python-part-1-practise/


    async def get_user(request):
        return json_response({'user': str(request.user)})

    async def auth_middleware(app, handler):
        async def middleware(request):
        request.user = None
        jwt_token = request.headers.get('authorization', None)
        if jwt_token:
            try:
                payload = jwt.decode(jwt_token, JWT_SECRET,
                                     algorithms=[JWT_ALGORITHM])
            except (jwt.DecodeError, jwt.ExpiredSignatureError):
                return json_response({'message': 'Token is invalid'}, status=400)

            request.user = User.objects.get(id=payload['user_id'])
        return await handler(request)
    return middleware

    app = web.Application(middlewares=[auth_middleware])
    app.router.add_route('GET', '/get-user', get_user)

**Comment by pgjones** [comment]
Yep, ASGI has a concept of middleware similar to the WSGI concept. [Here](https://pgjones.gitlab.io/quart/middleware.html) is a document that hopefully explains things.

**Comment by mthota15** [comment]
@pgjones can you provide full example how to map middleware with quart?

**Comment by pgjones** [comment]
The linked document should give you that example. What do you think is missing?

**Comment by mthota15** [comment]
Here is my code 

    from quart import Quart

    app = Quart(__name__)

    class TokenMiddleware:
        def __init__(self, app):
             self.app = app

        def __call__(self, scope):
           print(scope['headers'])
           for header, value in scope['headers']:
               if header == 'X-Secret' and value == 'very-secret':
                  return self.app(scope)
           return self.error_response

        async def error_response(self, receive, send):
            await send({
               'type': 'http.response.start',
               'status': 401,
               'headers': ['content-length', '0'],
         })
         await send({
            'type': 'http.response.body',
            'body': b'',
            'more_body': False,
        })

       TokenMiddleware(app)

     @app.route('/')
     async def index():
           return "Ok"

    if __name__ == '__main__':
           app.run()

I am trying to print the scope values in Middleware but when i run the code its not printing the scope values. I am not sure i am tying the right way to initialize the middleware.

**Comment by pgjones** [comment]
You need to distinguish between the Quart app and the TokenMiddleware app, and have the ASGI server serve the latter. I'd change it too,
```python
class TokenMiddleware:
    ...
    def run(self, *args, **kwargs):
        return self.app.run(*args, **kwargs)
    ...

app = TokenMiddleware(app)
if __name__ == '__main__':
       app.run()
```
