### ISSUE TITLE
HTTP/2 DoS Vulnerability

### ISSUE THREAD

**Issue by GalGoldshtein** [pgjones/quart#28]
Hi,

I would like to report a vulnerability in quart HTTP Server when serving HTTP/2 clients.

In section 10.5 of the HTTP/2 RFC an attack is described where an attacker is sending large SETTINGS frames that includes many settings inside it. 
We tested this scenario by opening many connections to the quart server and sending a SETTINGS frame with payload size of 14400 bytes and we were able to cause quart to consume all the machines memory and overload one CPU core with 100% usage by attacking from a single machine. 

It is also important to note that quart never closes the connection so the attacker can keep sending those malformed SETTINGS frames, and when under the attack described above, quart responds after a long period to new legitimate requests:

![image](https://user-images.githubusercontent.com/42509489/44307065-a8fe4400-a3a4-11e8-9f0f-d0a9430ae616.png)

![image](https://user-images.githubusercontent.com/42509489/44307098-245ff580-a3a5-11e8-9d13-bd7a9dfca267.png)

You can find the script that we used for attacking it and the script that was used to start the server instance in the following link: https://galgoldshtein.co.il/HTTP2/62c31461558c9be64089145736d0d5bf/HTTP2%20Settings%20Frame%20DoS.zip

Thanks.

**Comment by pgjones** [comment]
Thanks, could you list the h2 and hpack versions you used? Also could you put the code as gists?

**Comment by pgjones** [comment]
Thanks. I think the right approach is to allow the maximum frame size to be configured in the [hypercorn config](https://gitlab.com/pgjones/hypercorn/blob/master/hypercorn/config.py) (hypercorn is the default server for Quart) and change the timeout such that a client must send a request within the timeout or the connection is closed. What do you think about this?

**Comment by pgjones** [comment]
So the timeout part is implemented in https://gitlab.com/pgjones/hypercorn/commit/c5eecd776453182db6069718af3501e49d7367f2

**Comment by pgjones** [comment]
...and the frame size in (with a smaller default) https://gitlab.com/pgjones/hypercorn/commit/e7bb32e8fc6ca8d950a79cbab09fb7af7c13b568

I think this should be fixed now (when I next release).
