### ISSUE TITLE
ProxyFix?? O.o

### ISSUE THREAD

**Issue by tlaskyd** [pgjones/quart#31]
Hello.
I use Flask a lot, and Quart looks like good alternative, but I came across a little problem.
With Flask I used to do this:

`
from flask import Flask
from werkzeug.contrib.fixers import ProxyFix

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
`

This was easy way to get "real" client address behind proxy. But i can't find a way to do something similar in Quart. Is there / Will there be any solution? Thnaks...

**Comment by pgjones** [comment]
I think it is unlikely I'd add a `ProxyFit` to Quart, however it would be quite easy to implement as ASGI [middleware](https://pgjones.gitlab.io/quart/middleware.html) based on [ProxyFix](https://github.com/pallets/werkzeug/blob/master/werkzeug/contrib/fixers.py). Maybe you could post the gist here if you write it?

**Comment by erg** [comment]
I had a proxy issue using gunicorn and quart and nginx in AWS. The easy fix for me was to use hypercorn instead of gunicorn, and then ProxyFix is unnecessary.

**Comment by Jay484** [comment]
any update regarding proxyfit?
