### ISSUE TITLE
Why can't access global app outside context?

### ISSUE THREAD

**Issue by gy8409** [pgjones/quart#33]
I want to create an asycio task in Blueprint, and add_done_callback for it, which is used to delay the task execution in another event loop without hanging the current work. But I can't get current_app in callbacks.

Is it designed for not run task like this on purpose?
Here is my code.
```
@app.route('/someurl, methods=['POST'])
@admin_required(const.Role_Admin)
def create_something_in_db():
    # do something 
    task = asyncio.ensure_future(current_app.some_obj.really_time_consuming_task(args))
    task.add_done_callback(functools.partial(current_app.db_operator.save_result, arg))
```
It always crash on `current_app.db_operator.save_result` execution.

**Comment by pgjones** [comment]
Yep the `copy_current_app_context` decorator is required at the moment, however the next release (0.7.0 that targets Python 3.7 or better) will negate the need in this case - so soon :).
