### ISSUE TITLE
asgi scope type is unknown

### ISSUE THREAD

**Issue by nurettin** [pgjones/quart#34]
Hi, I started getting the following stack trace in the latest quart version:

> [2018-11-12 09:33:04,391] ASGI Framework Lifespan error, continuing without Lifespan support
> Traceback (most recent call last):
>   File "/home/nurettin/.local/share/virtualenvs/pylongrun-fEmL5R2s/lib/python3.6/site-packages/hypercorn/asyncio/lifespan.py", line 24, in handle_lifespan
>     asgi_instance = self.app(scope)
>   File "/home/nurettin/.local/share/virtualenvs/pylongrun-fEmL5R2s/lib/python3.6/site-packages/quart/app.py", line 1689, in __call__
>     raise RuntimeError('ASGI Scope type is unknown')
> RuntimeError: ASGI Scope type is unknown
> 12-Nov-18 09:33:04: quart.serving ERROR: ASGI Framework Lifespan error, continuing without Lifespan support
> Traceback (most recent call last):
>   File "/home/nurettin/.local/share/virtualenvs/pylongrun-fEmL5R2s/lib/python3.6/site-packages/hypercorn/asyncio/lifespan.py", line 24, in handle_lifespan
>     asgi_instance = self.app(scope)
>   File "/home/nurettin/.local/share/virtualenvs/pylongrun-fEmL5R2s/lib/python3.6/site-packages/quart/app.py", line 1689, in __call__
>     raise RuntimeError('ASGI Scope type is unknown')
> RuntimeError: ASGI Scope type is unknown
>

**Comment by nurettin** [comment]
whoops, I just saw this `and requires Python 3.7.0 or higher (see python version support for reasoning).`

**Comment by pgjones** [comment]
Does this cause a crash, or does the serving continue? 

It should just be a warning `ASGI Framework Lifespan error, continuing without Lifespan support`, with the serving continuing. Sadly it doesn't look to be as clear as I'd hoped.

**Comment by nurettin** [comment]
It is about type checking. lifespan handler doesn't specify http or websocket type, so we get this error.

After a few hours of debugging package by package I came to the same conclusion as the person below

https://gitlab.com/pgjones/quart/issues/159

>Brian May @penguin_brian · 10 hours ago
>The workaround seems to be to downgrade hypercorn from 0.4.0 to 0.3.2

**Comment by pgjones** [comment]
This should be fixed with 0eae5971e3c76bafe199dfe2deb0dfe5052fc78f and usable in the Hypercorn==0.4.1 release. Could you upgrade to Hypercorn 0.4.1?
