### ISSUE TITLE
http2_push example hangs when using nghttp

### ISSUE THREAD

**Issue by jonozzz** [pgjones/quart#37]
I was trying to verify the http2_push example by using nghttp. The example does seem to work fine from a browser (Chrome or Firefox). 

Repro:
> $ QUART_APP=http2_push:app quart run
> Running on https://127.0.0.1:5000 (CTRL + C to quit)
> [2018-12-19 14:44:13,507] ASGI Framework Lifespan error, continuing without Lifespan support
> 
> $ nghttp -nvy https://localhost:5000/push
>

**Comment by pgjones** [comment]
What is the output for it hanging? I reach,
```
[  0.239] recv DATA frame <length=122, flags=0x00, stream_id=64>
[  0.239] recv DATA frame <length=0, flags=0x01, stream_id=64>
          ; END_STREAM
```
which I think means it completes for me.

**Comment by jonozzz** [comment]
The GOAWAY is never sent, which makes me think that the client is still waiting for some data that never arrives.  If you disable push (--no-push), or access a different URL the session is closed correctly.

**Comment by pgjones** [comment]
I've found a few bugs from this report, so thanks :). Mostly though 764e0fe967f7fe6abb8baf4787a9609c5be7601b fixes the issue here. Could you try with master and check it is resolved for you?
