### ISSUE TITLE
make quart a PEP 561 compatible package

### ISSUE THREAD

**Issue by h4emp3** [pgjones/quart#38]
It is great to see a typed package, it sadly is still a rarity. Trying quart out for the first time and having mypy running in my vim and via a Makefile, I was surprised about it not wanting to use the quart's typing information.

According to [the mypy documentation](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages) it only does that when there is a `py.typed` file in the installed package. And sure enough, after creating that file (with `touch "$VIRTUAL_ENV/lib/python3.7/site-packages/quart/py.typed"`) it works like a charm.

I don't really know if there is another way to achieve this, but I think adding this file to the distribution would be the easiest way to just make it work out of the box.

**Comment by pgjones** [comment]
Did you install Quart >= 0.7.0? As the `py.typed` file should be [present](fba990a9e49ac6daaca7a481df72f819aacd5497)...

**Comment by h4emp3** [comment]
Oh wow, instant reply :D 
Yes, I just installed the latest version:
```
$ pip freeze --local | grep Quart
Quart==0.7.1
```

**Comment by h4emp3** [comment]
I guess the setuptools package_data option is really necessary to include the file in the dist package.

**Comment by pgjones** [comment]
I see, be0a9159b9b45c22462d625666ad75e1e552b2a7 should fix this (in the next release). Thanks for the report :)

**Comment by h4emp3** [comment]
Awesome, thanks a lot for the very fast fix! :)
I'm looking forward to using quart, it looks very promising and it really is the promised drop-in replacement for flask. Cheers and good luck with the project!
