### ISSUE TITLE
RuntimeError: Working outside of application context

### ISSUE THREAD

**Issue by mojimi** [pgjones/quart#42]
I don't understand why I'm still getting this error even after adding the proper context as per documentation

```python
@app.route('/')
async def pdf():
	asyncio.create_task(sendMail())
	return 'Done'
async def sendMail():
        async with app.app_context():
		print('sending mail')
		msg = Message(
			'Message',
			recipients=['myrecipient@myemail.com']
		)
		mail.send(msg)
```

**Comment by mojimi** [comment]
> 
> 
> It should work without the `async with app.app_context()` line then, have you tried that?
> Also what part of the documentation hints at needed this?

Well I've tried without async firstly, but now tried again, the error is:

`AttributeError: __enter__`

But with async it gives the proper outside context error.
are you sure it works with create_task? Since I already returned the response

The documentation is here : https://pgjones.gitlab.io/quart/source/quart.app.html#quart.app.Quart.app_context

**Comment by pgjones** [comment]
Hmm, I think this might be a bug with the app context being closed. I'll try looking.

Thanks for the link.

**Comment by mojimi** [comment]
> 
> 
> Hmm, I think this might be a bug with the app context being closed. I'll try looking.
> 
> Thanks for the link.

To be honest I'm not sure if keeping the app running after returning the response is a valid design choice.

Also to solve my problem I might be able to just code my own mail class and ditch flask-mail.

**Comment by pgjones** [comment]
Ah, I see what is happening here. You need to use the [Flask-Patch](https://pgjones.gitlab.io/quart/flask_extensions.html) system to use Flask-Mail. Basically just add `import quart.flask_patch` to the top of your main module.

**Comment by avatar-lavventura** [comment]
@pgjones https://pgjones.gitlab.io/quart/flask_extensions.html link seems dead, is it still working?

**Comment by pgjones** [comment]
The new link is https://pgjones.gitlab.io/quart/how_to_guides/flask_extensions.html, thanks
