### ISSUE TITLE
wrappers/request.py::_load_form_data broken for multipart/form-data

### ISSUE THREAD

**Issue by tjtaill** [pgjones/quart#43]
At line https://github.com/pgjones/quart/blob/master/quart/wrappers/request.py#L223

there is no way cgi.FieldStorage could possibly correctly parse multipart/form-data files upload without setting the limit to the content-length so the code should be
```python
content_length = self.headers['content-length']
field_storage = FieldStorage(
                io.BytesIO(raw_data), headers=self.headers, 
                environ={'REQUEST_METHOD': 'POST'}, limit=content_length
)
```
also at
https://github.com/pgjones/quart/blob/master/quart/wrappers/request.py#L240

sometimes the key is None and this code blows up because multidict only accepts str as key not None

so code should be
```python
elif key:
      self._form.add(key, field_storage_key.value)
```

With these two changes I get my unit test to pass which I have shown below
```python
from http import HTTPStatus
from copy import deepcopy
from datetime import datetime
from io import BytesIO
from PIL import Image
from werkzeug.test import encode_multipart
from werkzeug.datastructures import FileMultiDict

import pytest
from models import Documents


def create_test_image(name):
    buffered = BytesIO()
    image = Image.new('RGBA', size=(50, 50), color=(155, 0, 0))
    image.save(buffered, 'png')
    file = BytesIO(buffered.getvalue())
    file.name = name
    file.seek(0)
    return file


image_file = create_test_image('filename.png')
fmd = FileMultiDict()
fmd.add_file('file', image_file, filename='filename.png', content_type='image/png')

boundary = 'Test'

_, data = encode_multipart(fmd, boundary=boundary)

headers = {
    'Link': 'https://www.notawebhook.com',
    'Eai-Callback-Token': 'notAtoken',
    'Content-Type': 'multipart/form-data; boundary={}'.format(boundary),
    'Content-Length': len(data)
}

auth = 'Bearer {}'

@pytest.mark.asyncio
async def test_token_works(client, db, token):
    auth_headers = deepcopy(headers)
    auth_headers['Authorization'] = auth.format(token)
    # print('data: {}'.format(data))
    response = await client.post('/v0.0.1/files',
                                 data=data, headers=auth_headers)
    body = await response.json
    print(body)
    assert response.status_code == HTTPStatus.CREATED
    task_id = body['taskId']
    docs = Documents.query.filter_by(task_id=task_id).all()
    assert len(docs) == 1
    doc = docs[0]
    assert doc.page == 1
    assert doc.task_id == task_id
    assert type(doc.time_stamp) is datetime
    image_file.seek(0)
    assert doc.data == image_file.read()
```

**Comment by tjtaill** [comment]
From f51a4a44078d9033e500de1f7bb73912c1a33a51 Mon Sep 17 00:00:00 2001
From: tjtaill <troy.taillefer@elementai.com>
Date: Wed, 6 Feb 2019 20:20:17 -0500
Subject: [PATCH] ISSUE-43 multipart for data fails to parse correctly

There are two bugs when the request object tries to parse
a multipart form. First when key is None adding it to a multidict
fails since keys can only be str not None. Second cgi.FieldStorag
needs to have valid value for limit equalt to the content-length
to parse the multipart/form-data body correctly in case of files
the file data will be empty if this isn't provided
---
 quart/wrappers/request.py | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/quart/wrappers/request.py b/quart/wrappers/request.py
index 47befd8..09eea94 100644
--- a/quart/wrappers/request.py
+++ b/quart/wrappers/request.py
@@ -220,8 +220,10 @@ class Request(BaseRequestWebsocket, JSONMixin):
                 for value in values:
                     self._form.add(key, value)
         elif content_type == 'multipart/form-data':
+            limit = self.headers['content-length']
             field_storage = FieldStorage(
-                io.BytesIO(raw_data), headers=self.headers, environ={'REQUEST_METHOD': 'POST'},
+                io.BytesIO(raw_data), headers=self.headers,
+                environ={'REQUEST_METHOD': 'POST'}, limit=limit,
             )
             for key in field_storage:  # type: ignore
                 field_storage_key = field_storage[key]
@@ -236,7 +238,7 @@ class Request(BaseRequestWebsocket, JSONMixin):
                         io.BytesIO(field_storage_key.file.read()), field_storage_key.filename,
                         field_storage_key.name, field_storage_key.type, field_storage_key.headers,  # type: ignore # noqa: E501
                     )
-                else:
+                elif key:
                     self._form.add(key, field_storage_key.value)
 
     @property
-- 
2.20.1

**Comment by pgjones** [comment]
Thank you @tjtaill , this is great. I've applied it to the master branch and the 0.6-maintenance branch. I'm not likely to release for a while though, unless this is pressing for you?

I've a pending TODO for the multipart handling (including being able to send multipart when using the testing client) - so I'll hopefully add tests then.

**Comment by tjtaill** [comment]
@pgjones No problem I have a patched version in my private pypi repo that I am using for now.
I do need to have a multipart file up[load endpoint but 

 >> including being able to send multipart when using the testing client
That is cool like the requests library can take the files argument ?

**Comment by tjtaill** [comment]
By the way I like this lib https://github.com/siddhantgoel/streaming-form-data/ for doing multipart parsing I am using it as a validator since cgi.FieldStroage seems to try to parse garbage as well

**Comment by pgjones** [comment]
That looks interesting, do you know if allows you to construct the raw bytes to send as well? (I couldn't find anything that suggested it did).

**Comment by pgjones** [comment]
Changed my mind, 0.8.1 has just been released.

**Comment by tjtaill** [comment]
> That looks interesting, do you know if allows you to construct the raw bytes to send as well? (I couldn't find anything that suggested it did).

No it doesn't seem to do, for that I use `from werkzeug.test import encode_multipart` it does the job and do not need new dependency. There is also https://github.com/requests/toolbelt MultipartEncoder that does that job really well too
