### ISSUE TITLE
Certbot certificate installation > running Quart on https

### ISSUE THREAD

**Issue by kllr** [pgjones/quart#45]
Hi,

It may be a bit off topic, but i can't find an answer on the net... Sorry if this is a noob question.

Has anybody installed a certificate with certbot for a Quart/Hypercorn server?
I have a converted project from Flask to Quart. In Flask i used an Apache2 webserver. Installing the certificate was very easy.

I made a new server and i'm trying certbot with webroot right now. This is giving me an error.

> 
> > sudo certbot certonly
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 
> How would you like to authenticate with the ACME CA?
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 1: Apache Web Server plugin - Beta (apache)
> 2: Spin up a temporary webserver (standalone)
> 3: Place files in webroot directory (webroot)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Select the appropriate number [1-3] then [enter] (press 'c' to cancel): c
> Could not choose appropriate plugin: authenticator could not be determined or is not installed
> authenticator could not be determined or is not installed
> ubuntu@ip-172-xx-31-4:~$ sudo -s
> root@ip-172-31-xx-4:~# sudo certbot certonly
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 
> How would you like to authenticate with the ACME CA?
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 1: Apache Web Server plugin - Beta (apache)
> 2: Spin up a temporary webserver (standalone)
> 3: Place files in webroot directory (webroot)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 3
> Plugins selected: Authenticator webroot, Installer None
> Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
> to cancel): makemesmile.nl
> Obtaining a new certificate
> Performing the following challenges:
> http-01 challenge for xxxx.nl
> Input the webroot for xxxxx.nl: (Enter 'c' to cancel): /var/www/
> Waiting for verification...
> Cleaning up challenges
> Failed authorization procedure. makemesmile.nl (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient                   authorization :: Invalid response from 
> 
> > http://xxxxx.nl/.well-known/acme-challenge/6sXI6Av

Do i need to do something with a route for '/.well-known/'? Or is it something completely different?

**Comment by kllr** [comment]
Hi,

It may be a bit off topic, but i can't find an answer on the net... Sorry if this is a noob question.

Has anybody installed a certificate with certbot for a Quart/Hypercorn server?
I have a converted project from Flask to Quart. In Flask i used an Apache2 webserver. Installing the certificate was very easy.

I made a new server and i'm trying certbot with webroot right now. This is giving me an error.

> 
> > sudo certbot certonly
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 
> How would you like to authenticate with the ACME CA?
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 1: Apache Web Server plugin - Beta (apache)
> 2: Spin up a temporary webserver (standalone)
> 3: Place files in webroot directory (webroot)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Select the appropriate number [1-3] then [enter] (press 'c' to cancel): c
> Could not choose appropriate plugin: authenticator could not be determined or is not installed
> authenticator could not be determined or is not installed
> ubuntu@ip-172-xx-31-4:~$ sudo -s
> root@ip-172-31-xx-4:~# sudo certbot certonly
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 
> How would you like to authenticate with the ACME CA?
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 1: Apache Web Server plugin - Beta (apache)
> 2: Spin up a temporary webserver (standalone)
> 3: Place files in webroot directory (webroot)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 3
> Plugins selected: Authenticator webroot, Installer None
> Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
> to cancel): makemesmile.nl
> Obtaining a new certificate
> Performing the following challenges:
> http-01 challenge for xxxx.nl
> Input the webroot for xxxxx.nl: (Enter 'c' to cancel): /var/www/
> Waiting for verification...
> Cleaning up challenges
> Failed authorization procedure. makemesmile.nl (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient                   authorization :: Invalid response from 
> 
> > http://xxxxx.nl/.well-known/acme-challenge/6sXI6Av

Do i need to do something with a route for '/.well-known/'? Or is it something completely different?

**Comment by kllr** [comment]
One step further;
When i run the server:
`hypercorn --bind ec2-18-222-XXX-XXX.us-east-2.compute.amazonaws.com:80 vote:app`
and then:
sudo certbot certonly --webroot -w /home/ubuntu/vote -d sitename.nl 
the certificate installs...

But now i still get a timeout running the site.
I kill the server on port 80, and then restart it like this:
`hypercorn --bind ec2-18-222-XXX-XXX.us-east-2.compute.amazonaws.com:443 vote:app`

Any suggestions?

**Comment by kllr** [comment]
`hypercorn --certfile /etc/letsencrypt/csr/0006_csr-certbot.pem  --keyfile /etc/letsencrypt/keys/0006_key-certbot.pem --bind ec2-18-222-xxx-xxx.us-east-2.compute.amazonaws.com:443 vote:app`

Tried this as well but this gives error:
SSLError: [SSL] PEM lib (_ssl.c:3717)
```

hypercorn/config.py in create_ssl_context at line 107
        try:
            context.set_npn_protocols(["h2", "http/1.1"])
        except NotImplementedError:
            pass  # NPN is not necessarily available
        context.load_cert_chain(certfile=self.certfile, keyfile=self.keyfile)
        if self.ca_certs is not None:
            context.load_verify_locations(self.ca_certs)
        return context

```

**Comment by pgjones** [comment]
I'm not familiar with certbot, but you seem to have that working. The SSLError seems to suggest it has an issue with the keyfile are you sure `/etc/letsencrypt/keys/0006_key-certbot.pem` is the private key? [This](https://superuser.com/questions/1194523/lets-encrypt-certbot-where-is-the-private-key) could be the relevant answer.

**Comment by kllr** [comment]
Hi,

Thanks!! You were totally right. Sorry for wasting your precious time.

`hypercorn --certfile /etc/letsencrypt/live/sitename.nl/cert.pem  --keyfile /etc/letsencrypt/live/sitename.nl/privkey.pem --bind ec2-18-222-xxx-xxx.us-east-2.compute.amazonaws.com:443 vote:app`

This did the trick. All is running very well :)

**Comment by pgjones** [comment]
Great, I'm glad you figured it out.
