### ISSUE TITLE
How to get user_agent from quart request

### ISSUE THREAD

**Issue by Alevsk** [pgjones/quart#51]
Hi, currently I'm migrating a small service from flask to quart and Im facing an issue related to request
`
from quart import request
`
It seems like request from quart doesn't have request.user_agent.platform nor request.user_agent.browser, however request from flask have them.

Are there any plan to add this? or there is any workaround ?

**Comment by pgjones** [comment]
I would use [UA-Parser](https://github.com/ua-parser/uap-python) and `request.headers["User-Agent"]`.

I'm not sure whether to add it, it seems tangential and something better supported in that library than in Werkzeug. I'm tempted to add it using that library as an optional extra.

**Comment by Alevsk** [comment]
Thanks for the workaround, it works!
