### ISSUE TITLE
Is there a compatible performance profiler for Quart

### ISSUE THREAD

**Issue by DeVonteApplewhite** [pgjones/quart#52]
I see that there are profiler packages that can give performance metrics on views as they are used during the runtime of the app. I wanted to use such a tool to identify bottlenecks in the views. Is there something that works with Quart apps?

**Comment by pgjones** [comment]
Not that I'm aware of, I think you could adapt Flask-Profiler by adding async/await keywords though.

**Comment by DeVonteApplewhite** [comment]
Thanks, I'll try that.
