### ISSUE TITLE
negative indices in session dictionary

### ISSUE THREAD

**Issue by kllr** [pgjones/quart#54]
Hi,

I've written a simple shopping cart in session.

When i'm trying to remove items from the cart it goes wrong. With normal iteration through the dictionary, it doesn't delete all items when i ask it to.
Playing with it, i came to the solution below. It seems that the range of the cart items begins at a negative index. 

Am i seeing this wrong ? Or am i doing something wrong? Or is it just a bug?
```python
cart_items = session["cart"]
for index in range(-1*len(cart_items),0):
    if remove_all:
        session['cart'].remove(cart_items[index])
    else:
        if str(cart_items[index]) == identifier:
            session['cart'].remove(cart_items[index])
            break
```

cheers,

**Comment by pgjones** [comment]
I think the issue you are facing here is that you are trying to remove items from a list whilst iterating over it. [This](https://unspecified.wordpress.com/2009/02/12/thou-shalt-not-modify-a-list-during-iteration/) seems like it would explain it.
