### ISSUE TITLE
websocket.receive() binary data

### ISSUE THREAD

**Issue by jbq** [pgjones/quart#57]
Hi, I'm successfully using Quart's websocket, and I'm now wondering why `websocket.receive()` returns `str` is there a way to get `bytes` instead?  I'm working with a binary protocol, so it would be nice to have raw data access and it sounds weird to encode the input.

**Comment by pgjones** [comment]
It should return either str or bytes ([`AnyStr`](https://github.com/pgjones/quart/blob/master/quart/wrappers/request.py#L305)) depending on what the client sends. There may be a bug if it is decoding the bytes.

**Comment by jbq** [comment]
It may be my bad, part of my code was still sending `str`.  The Quart Websocket documentation does has no example with binary and doesn't mention it, hence my question.

**Comment by pgjones** [comment]
No worries, I've added some more documentation here 72bd6e9473867116814b59bc22c04dfe3b2cdd15.
