### ISSUE TITLE
Bug: Form with enctype 'multipart/form-data' in Quart version > 0.72

### ISSUE THREAD

**Issue by kllr** [pgjones/quart#59]
Hi,

I've got a form that returns a picture. So the enctype is 'multipart/form-data'. 
Last week the form worked. Now it doesnt anymore.
In between i updated quart to 0.81 and i get the error message stated in the attachment.
`"TypeError unsupported operand type(s) for -: 'str' and 'int'"`

What i tried:
- jumping back to quart 0.72 fixed the issue
- quart 0.81: emptying the whole form (html) resolves the error, adding 1 random field and the error is back 
- quarto 0.81: Removing the enctype  and the form does not give error messages anymore.

[error.zip](https://github.com/pgjones/quart/files/3005312/error.zip)

kind regards,
steven

**Comment by pgjones** [comment]
I believe this is fixed in master, 483ba634c5c17b3e63b8a8096c590828866589df. Does this work for you?

**Comment by kllr** [comment]
Works like a charm, thanks!
 I'll go and edit the file on the server for now as well.
