### ISSUE TITLE
How to integrate quart with queue system?

### ISSUE THREAD

**Issue by Urahara** [pgjones/quart#6]
So i running Quart with gunicorn, but i facing this problem:

https://github.com/benoitc/gunicorn/issues/1700

I thinking that workers will not solve my problem described above that sometimes the tasks freezing leaving without any response. So i think maybe if i start using Redis to manage this tasks will be more useful since i have scalability in mind. Is there any alternative to gunicorn? I configurating my app wrong?

I have 2 cpus cores:

`gunicorn --worker-class quart.worker.GunicornWorker -w 2 server:app -b 0.0.0.0:8080 -t 600`

**Comment by pgjones** [comment]
In your gunicorn report you mention scrapy, which looks as if it will block on IO, thereby blocking the entire GunicornWorker. So potentially if both workers are scraping something that takes time on the IO and then continues to take CPU time without yielding or interacting with the asyncio event loop it will block and prevent other actions as you state. (Sadly scrapy doesn't [look like](https://github.com/scrapy/scrapy/issues/3106) it supports asyncio)

I think you should try [asyncio.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_in_executor) to run your scrapy code. For example,

```python

def func_that_does_scrapy():
    ...
    return results

@app.route('/')
await def do_scrapy():
    results = await asyncio.run_in_executor(None, func_that_does_scrapy)
    ...
    return ''
```

As this allows code that doesn't interact with asyncio (scrapy) to run on another thread and hence not block the main event loop.

**Comment by Urahara** [comment]
Thanks @pgjones i will test this out! I was thinking that scrapy is not running on loop, but i was wrong.
