### ISSUE TITLE
Trying to run tortoise with quart async rest api

### ISSUE THREAD

**Issue by shaloba** [pgjones/quart#60]
**Describe the bug**
Hi, 

I have simple tortoise example that work fine when i create the python event loop and run it.
but when i run Quart API server I get strange error, I braked my head trying to figure out what is the issue 
Although the error is in tortoise but i will appreciate if you can direct me maybe to extra configuration 
(I'm running python3.7)
The script I ran is below: 

```
import asyncio
from tortoise import Tortoise, fields
from tortoise.models import Model

from quart import Quart, request, abort

app = Quart(__name__)
app.config.from_object(config)

class Users(Model):
    id = fields.IntField(pk=True)
    status = fields.CharField(20)
    def __repr__(self):
        return str(self.id)

class Workers(Model):
    id = fields.IntField(pk=True)
    status = fields.CharField(20)
    def __repr__(self):
        return str(self.id)

@app.before_first_request
async def initial_db():
    await Tortoise.init({
        'connections': {
            'default':  "postgres://localhost:5432/db",
            'second':  "postgres://localhost:5432/db",
        },
        'apps': {
            'users': {
                'models': ['__main__'],
                'default_connection': 'default',
            },
            'workers': {
                'models': ['__main__'],
                'default_connection': 'second',
            }
        }
    })


def run_quart():
    app.run(port=5002)


def run_tortoise():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(initial_db())

if __name__ == '__main__':
    # run_quart() # not working
    run_tortoise() # working
```

**To Reproduce**
run one time the "run_quart" see the error
then run "run_tortoise" see the run succeed

**Expected behavior**
tortoise ORM will use the Quart event loop

**Actual behavior**
Tortoise raise "NotADirectoryError" error

**Additional context**
This is my first time using Quart ORM and its looking very cool, I will appreciate any help with this issue 

Thanks in advanced!

**Comment by pgjones** [comment]
Looks like https://github.com/tortoise/tortoise-orm/issues/119 has the solution.

**Comment by shaloba** [comment]
@pgjones actually the solution didn't work for me and raise the same error :/

**Comment by shaloba** [comment]
Actually turns out the solution works! **but**  only on python 3.6 (i used python 3.7)

link to solution 
https://github.com/tortoise/tortoise-orm/issues/119

thanks to @grigi

**Comment by grigi** [comment]
It works on Py3.7 for me too, fyi. I suspect there is an environment issue at play?

**Comment by shaloba** [comment]
@grigi  thanks for monitoring this one :) 
Its strange but on clean 3.7 environment its raising the "NotADirectoryError" but since im not bind to 3.7 and can work on 3.6 I can continue my project 

Thanks again your reply was really helpful :)
