### ISSUE TITLE
If more than 1 file is sent in a form, it will be in request.form, not request.files

### ISSUE THREAD

**Issue by FranciscoSilveira** [pgjones/quart#63]
### Expected behavior
All files submitted through a HTML form with POST should be in FileStorage objects inside request.files, regardless of how many.

### Observed behavior
When we have a HTML form with `enctype=multipart/form-data` and inside it an input with `type=file`, if a single file is selected and the form is submitted then it will be inside the awaitable request.files, but if instead we submit 2 or more files then they will be inside request.form.
__If the enctype is removed, then the file(s) will be inside request.form, no matter how many.__

### Steps to reproduce
The code snippet below shows this behavior:
**app.py**
```
from quart import Quart, request, render_template

app = Quart(__name__)

@app.route("/", methods=["GET", "POST"])
async def new_thread():
	if request.method == "GET":
		return await render_template("index.html")
	else:
		form = await request.form
		request_files = await request.files
		
		if "myfiles" in form:
			return "Files inside form"
		
		elif "myfiles" in request_files:
			return "Files in file section"
        
		else:
			return "No files"


if __name__ == "__main__":
	app.run()
```
	
**templates/index.html**
```
<html>
	<body>
		<form enctype=multipart/form-data method=POST>
			<input type=file name=myfiles multiple><br>
			<input type=submit>
		</form>
	</body>
</html>
```

**Comment by pgjones** [comment]
Seems like a bug, I'll look into it.

**Comment by pgjones** [comment]
Thanks @FranciscoSilveira I've fixed this in c663ffe1934a8a2237567db9e6077c88d0e5523e and I'll hopefully release 0.9.1 later today. Could you check it works for you?

**Comment by FranciscoSilveira** [comment]
Hey again, sorry for the huge delay. The issue is indeed fixed, thank you. One minor thing is that doing something like
```
request_files = await request.files
files = request_files.get("myfiles")
```
where `myfiles` is the name of the HTML file input, will give me a non-empty list in `files` even if the input was submitted empty (basically submitting the form with no file). A hotfix for this is to check if `len(files)==1 and files[0].filename==""`, which means it only contains an empty FileStorage. I can try to take a look at the code and fix this properly.

**Comment by pgjones** [comment]
I think this follows Flask (Werkzeug) which also returns a FieldStorage object.
