### ISSUE TITLE
Does quart have feature parity and consistent bug fixes for the python 3.6 and python 3.7 releases?

### ISSUE THREAD

**Issue by DeVonteApplewhite** [pgjones/quart#66]
I noticed that when I look at the available quart versions for python 3.6 and 3.7, they differ.
python 3.6:
0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13

python 3.7:
0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1

Do I need to use python 3.7 to get the latest quart changes? Will quart support and updates for python 3.6 at any point be deprecated?

Thanks.

**Comment by pgjones** [comment]
I'm supporting the a 0.6 branch until Python 3.8 is released. So you can get the latest bugfixes for 3.6 in 0.6 and features in 0.9 (currently). I've written some [documentation](https://pgjones.gitlab.io/quart/python_versions.html) to help explain this.
