### ISSUE TITLE
Any ways to call a function after a view sends a response?

### ISSUE THREAD

**Issue by McSpidey** [pgjones/quart#67]
I believe this was missing in Flask and needing to be impleented via wsgi middleware.  What's the best way of doing this with Quart? A response teardown injection of sorts.

**Comment by pgjones** [comment]
Do you mean to spawn something in the background? As you can always do `asyncio.ensure_future`, see [these docs](https://pgjones.gitlab.io/quart/background_tasks.html).

**Comment by SyamaMishra** [comment]
No, in this case I had a c dll known to cause a memory leak I wanted to run a clean up routine after the response was sent which used its contents. I've managed to fix the leak but still thought having a post  response callback might be useful.

**Comment by McSpidey** [comment]
No, in this case I had a c dll known to cause a memory leak I wanted to run a clean up routine after the response was sent which used its contents. I've managed to fix the leak but still thought having a post response callback might be useful.

**Comment by pgjones** [comment]
I think it would do what you want, something like,
```python
@app.route("/")
async def index():
    dll = ...
    response = ...
    asyncio.ensure_future(cleanup_dll(dll))
    return response
    # cleanup_dll runs sometime after the return
```

**Comment by McSpidey** [comment]
Thanks.
