### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'send'

### ISSUE THREAD

**Issue by juleski** [pgjones/quart#68]
Hi, I am trying to run quart in aws lambda in our production env. I can't get a proper response since it's throwing the ff. error

```
Traceback (most recent call last):
  File "/Users/jules/Repositories/snaaap/snaaap_v3/merchant-api/venv/lib/python3.7/site-packages/werkzeug/debug/__init__.py", line 288, in debug_application
    app_iter = self.app(environ, start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
```

I am using the  [Serverless Framework](https://serverless.com/) to develop and am using the ff serverless plugins:
* [Serverless wsgi](https://github.com/logandk/serverless-wsgi)
* [Serverless python requirements](https://github.com/UnitedIncome/serverless-python-requirements)

I saw that quart does not use the werkzeug package, the werkzeug package is **required** in serverless wsgi to be able to run the application in lambda. Can't seem to debug where the error in `send` is coming from. I would suspect it's one of the async libraries used.

Hope to hear from you soon!

**Comment by pgjones** [comment]
Quart is an ASGI framework, rather than a WSGI framework, which means that it cannot work with serverless. It can work with [Mangum](https://github.com/erm/mangum), which is an ASGI alternative to serverless.

**Comment by juleski** [comment]
Ok thanks @pgjones !
