### ISSUE TITLE
question regarding websockets

### ISSUE THREAD

**Issue by juntiedt2** [pgjones/quart#7]
currently I am running a flask web server on the same raspi3 where I also read a lot of sensors (IOT) which are send to the web page. Now I want to split data collection and Webserver to run on two or more Raspis. The data collection Raspis should send data via websocket to the webserver and receive input from the webserver initiated on the webpage. Will quart be able to handle these additonal websockets within the webserver app and how would this be coded? I apprecaite very much your support and suggestions in this matter.

**Comment by pgjones** [comment]
I think you are asking can quart listen to websockets and respond to data sent over them, if so the answer is [yes](https://pgjones.gitlab.io/quart/websocket_tutorial.html). In the most simple sense you need only add:
```python
from quart import websocket

@app.websocket('/ws')
async def ws():
    while True:
        data = await websocket.receive()
        # do something with the data
```
to listen to data over a websocket on the `/ws` path.

**Comment by juntiedt2** [comment]
That looks very promising. Which websocket client library would you recommend for the raspberry pis sending data to the quart server and receiving commands from the quart server in order to switch relays for example?

**Comment by pgjones** [comment]
I quite like [websockets](https://github.com/aaugustin/websockets) as a client library (and server if I need only websockets).
