### ISSUE TITLE
json.loads incorrctly annotated as returning a string

### ISSUE THREAD

**Issue by paul-griffith** [pgjones/quart#70]
https://github.com/pgjones/quart/blob/317562ea660edb7159efc20fa57b95223d408ea0/quart/json/__init__.py#L32

json.loads doesn't return a string, it accepts a string and returns an object. Maybe return should be `Union[dict, list]`? I don't know how strict the actual json lib is about return types

**Comment by pgjones** [comment]
Thanks, I've fixed this in 2eaae8dd0c5286a1751a76c2afb14759c0569e2f. The return is `Any` in Typeshed so I've followed suit.
