### ISSUE TITLE
Access Logs don't show with Hypercorn==0.7.0

### ISSUE THREAD

**Issue by cijo-uc** [pgjones/quart#72]
Quart version: 0.9.0
Hypercorn version: 0.7.0

```python
from quart import Quart


app = Quart(__name__)
app.config.from_object(__name__)


@app.route('/check/', methods=['GET'])
async def sample_method():
    return 'OK', 200


if __name__ == '__main__':
    app.run(port=9876, host='0.0.0.0')
```

Access logs show when I downgraded to hypercorn==0.6.0

**Comment by pgjones** [comment]
Thanks, this is fixed in 0159f0f553964339caf2fb1e5346a28cf66fa737 (master).

**Comment by cijo-uc** [comment]
Thanks. When will you be pushing this to pypi?

**Comment by pgjones** [comment]
Not sure at the moment, I've got a fair few things to do first.

**Comment by cijo-uc** [comment]
Sure Thanks :)

**Comment by pgjones** [comment]
Pushed now.

**Comment by cijo-uc** [comment]
Great! Thanks @pgjones
