### ISSUE TITLE
send_file() with BytesIO objects not working

### ISSUE THREAD

**Issue by McSpidey** [pgjones/quart#73]
Hi

I'm trying to use Quart to send a Pillow object from memory using send_file() via io.BytesIO but unfortunately it's giving a type error.

Code:
```
from PIL import Image
import io

pil_img = Image.open(file_path)

output = io.BytesIO()
pil_img.save(output, format='PNG')
output.seek(0)

return await send_file(output, mimetype='image/png')
```

Error:
`
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
`

Any help here is appreciated.

**Comment by pgjones** [comment]
Hi @McSpidey, could you try out the [`io` branch](https://gitlab.com/pgjones/quart/tree/io), specifically [this commit](https://gitlab.com/pgjones/quart/commit/985de53a17bfd621d0efb093dea384d0ca9acf95) and let me know if it solves this problem?

**Comment by McSpidey** [comment]
This appears to be working, thanks :)

**Comment by pgjones** [comment]
Thanks for testing, I've merged into master (an edited commit). I hope to release within the next 2 weeks.
