### ISSUE TITLE
Google Login Using Quart

### ISSUE THREAD

**Issue by yasersakkaf** [pgjones/quart#74]
Hi Jones,

I have this tutorial to implement Google Login with Flask.
https://www.mattbutton.com/2019/01/05/google-authentication-with-python-and-flask/

Can you give an equivalent code with Quart.

Thanks in Advance

**Comment by pgjones** [comment]
I've not used Google Login before, so I'm not sure how to use it. I have found this library though, [aiogoogle](https://github.com/omarryhan/aiogoogle) that looks to be an async version of the google libraries referenced in that article. I can help if you hit issues - just don't know enough to do the whole job.

**Comment by yasersakkaf** [comment]
Thanks for replying,
I will the library you mentioned.
