### ISSUE TITLE
[QUESTION] Any Quart http2 post/get example?

### ISSUE THREAD

**Issue by GnubiBORED** [pgjones/quart#75]
Im searching in documentation but i cannot find it anyone, how i can do a http2 post/get using quart

**Comment by pgjones** [comment]
You don't need to do anything, if you serve Quart using Hypercorn (the default) or Daphne, it will answer POST/GET requests made over HTTP/2.

If you want to send a POST/GET request you need a client library, such as [httpx](https://github.com/encode/httpx).
