### ISSUE TITLE
Is there a cleaner way to shutdown app from itself?

### ISSUE THREAD

**Issue by QwertyJack** [pgjones/quart#76]
I would like to add a heath probe to quart app. The server shutdowns itself when something goes wrong so that the upper level could restart the server automatically.
I'm not sure if this is the proper way, but the code goes:
```python
...
async def health_probe(url, timeout=3):
    # here we check the health 
    if fail:
        for task in asyncio.Task.all_tasks():
            task.cancel()

async def main():
    # bind the health probe together with the main loop
    import nest_asyncio
    nest_asyncio.apply()

    task = asyncio.create_task(health_probe('http://localhost:5000/healthz'))
    app.run(loop=task.get_loop())


if __name__ == "__main__":
    asyncio.run(main())
```

It really does work. Howevert, it complains that
```
ASGI Framework Lifespan error, continuing without Lifespan support
Traceback (most recent call last):
  File "/home/jack/.virtualenvs/flask/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 30, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "/home/jack/.virtualenvs/flask/lib/python3.7/site-packages/hypercorn/utils.py", line 183, in invoke_asgi
    await app(scope, receive, send)
  File "/home/jack/.virtualenvs/flask/lib/python3.7/site-packages/quart/app.py", line 1771, in __call__
    await asgi_handler(receive, send)
  File "/home/jack/.virtualenvs/flask/lib/python3.7/site-packages/quart/asgi.py", line 203, in __call__
    event = await receive()
  File "/home/jack/.virtualenvs/flask/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 63, in asgi_receive
    return await self.app_queue.get()
  File "/usr/lib/python3.7/asyncio/queues.py", line 159, in get
    await getter
concurrent.futures._base.CancelledError
```
It seems that catching the `CancelledError` doesn't help.
Any idea is appreciated.

**Comment by pgjones** [comment]
Not at the moment (other than calling `sys.exit()` for a harsh shutdown). For this to work support needs to be added to ASGI first, see https://github.com/django/asgiref/pull/113 .

## Off topic

I'd recommend not using `nest_asyncio` as does not work well with Quart, given your snippet I think you could just do,
```python

async def main():
    # bind the health probe together with the main loop
    asyncio.ensure_future(health_probe('http://localhost:5000/healthz'))
    app.run(loop=asyncio.get_current_loop())
```

I'd also recommend not using app.run in production, and instead using [Hypercorn serve](https://pgjones.gitlab.io/hypercorn/api_usage.html) as so,

```python
from hypercorn.asyncio import serve
from hypercorn.config import Config

async def main():
    # bind the health probe together with the main loop
    asyncio.ensure_future(health_probe('http://localhost:5000/healthz'))
    await serve(app, Config())
```

**Comment by QwertyJack** [comment]
I see. Thank you very much :)

**Comment by YuvrajGeek** [comment]
> Not at the moment (other than calling `sys.exit()` for a harsh shutdown). For this to work support needs to be added to ASGI first, see [django/asgiref#113](https://github.com/django/asgiref/pull/113) .
> 
> ## Off topic
> I'd recommend not using `nest_asyncio` as does not work well with Quart, given your snippet I think you could just do,
> 
> ```python
> async def main():
>     # bind the health probe together with the main loop
>     asyncio.ensure_future(health_probe('http://localhost:5000/healthz'))
>     app.run(loop=asyncio.get_current_loop())
> ```
> 
> I'd also recommend not using app.run in production, and instead using [Hypercorn serve](https://pgjones.gitlab.io/hypercorn/api_usage.html) as so,
> 
> ```python
> from hypercorn.asyncio import serve
> from hypercorn.config import Config
> 
> async def main():
>     # bind the health probe together with the main loop
>     asyncio.ensure_future(health_probe('http://localhost:5000/healthz'))
>     await serve(app, Config())
> ```

I believe you meant to send this link: https://pgjones.gitlab.io/hypercorn/how_to_guides/api_usage.html for the docs to Hypercorn serve.

**Comment by parity3** [comment]
I've had success on hypercorn trio shutting down while inside a request here:

```python
from quart.wrappers.response import DataBody
import json
import os
import trio
from hypercorn.trio.run import worker_serve, load_application
from hypercorn import Config

class AfterDataBody(DataBody):
    def __init__(self, data: bytes, do_stuff_callback: callable):
        super().__init__(data)
        self.do_stuff_callback = do_stuff_callback

    async def __aexit__(self, exc_type: type, exc_value: BaseException, tb: TracebackType) -> None:
        self.do_stuff_callback()

app = QuartTrio(__name__)

@app.route('/stop', methods=['POST'])
async def stop(app):
    return AfterDataBody(json.dumps({'status': 'OK'}).encode(), app.shutdown_event.set)

async def async_run(config: Config, app: App):
    app.shutdown_event = trio.Event()
    await worker_serve(app, config, shutdown_trigger=app.shutdown_event.wait)

def main():
    config = Config()
    trio.run(async_run, config, app)

if __name__ == "__main__":
    main()
```

That's a ton of scaffolding but the main points are:

- make an event or awaitable and set it on the app instance before calling into hypercorn's worker_serve, 
- trigger the shutdown in the exit context of the response body to make sure the last response has been fully delivered
- I don't think there's any built in support for un-binding and draining connections before shutting down.. there's just a "grace period".
