### ISSUE TITLE
Motor MongoDB driver integration with Quart 

### ISSUE THREAD

**Issue by harshakumar347** [pgjones/quart#77]
Hi currently Flask doesn't  support Motor driver for Mogodb but it supports MongoEngine which uses PyMongo driver internally which not asynchronous. Since Quart framework is built around Async IO, It will be much better if this paradigm is implemented in MongoDB Integration as well. And also Motor runs on async io. Is it possible to implement  MotorEngine instead of MongoEngine  for quart

**Comment by pgjones** [comment]
This [MotorEngine](https://github.com/heynemann/motorengine) seems to be tailed to work with Tornado only, so I don't think it would work with Flask or Quart. [Motor](https://github.com/mongodb/motor) seems to support asyncio though, so I think that would work with Quart.

Sorry, I've not used MongoDB in Python so I don't have a suggestion. I'll leave this open. (There was a similar question in this [issue](https://gitlab.com/pgjones/quart/issues/161).)
