### ISSUE TITLE
How to use gunicorn with Quart

### ISSUE THREAD

**Issue by bhushanbrb** [pgjones/quart#78]
this is not an issue -- 
Used **quart** as replacement for **_Flask_** but while used gunicorn with **worker_class** = _**'quart.worker.GunicornUVLoopWorker'**_ got error quart.worker not found. Kindly suggest how to use gunicorn or other alternative to use

**Comment by pgjones** [comment]
Please switch to [Hypercorn](https://gitlab.com/pgjones/hypercorn) (roughly the same arguments and configuration as Gunicorn) or any other ASGI server.
