### ISSUE TITLE
Exception when processing ACCEPT headers

### ISSUE THREAD

**Issue by claws** [pgjones/quart#8]
I built a Quart web server to serve some dynamic KML content. GoogleEarth supports two formats; KML and KMZ. I want to support returning a response in either of the supported formats. 

My code looks something like this:
``` python3
kml_mimetype = 'application/vnd.google-earth.kml+xml'
kmz_mimetype = 'application/vnd.google-earth.kmz'
SUPPORTED_MIMETYPES = (kmz_mimetype, kml_mimetype)

@app.route('kml_update', method=['GET'])
async def handle_kml_update():
    ''' Handle a request to the /kml_update route. '''
    try:
        mimetype = request.accept_mimetypes.best_match(
                SUPPORTED_MIMETYPES, default=kml_mimetype)
    except Exception:
        logger.exception('Error generating KML')
```

When GoogleEarth attempts to fetch data from the Quart web server's ``/kml_update`` route (which it is instructed to do via a KML file containing a NetworkLink tag) I observe an error in my handler function which is generated from Quart when it is processing the Accept headers.
``` python3
Error generating KML
Traceback (most recent call last):
  File "server.py", line 174, in handle_kml_update
    mimetype = request.accept_mimetypes.best_match(
  File "/Users/claws/.venvs/myenv/lib/python3.6/site-packages/quart/local.py", line 108, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/claws/.venvs/myenv/lib/python3.6/site-packages/quart/wrappers.py", line 291, in accept_mimetypes
    return MIMEAccept(self.headers.get('Accept', ''))
  File "/Users/claws/.venvs/myenv/lib/python3.6/site-packages/quart/datastructures.py", line 144, in __init__
    quality = float(raw_quality.split('=', 1)[-1])
ValueError: could not convert string to float: 'context.kml'
```

The ACCEPT headers in the request that triggered the error were:
``` python3
'Accept': 'application/vnd.google-earth.kml+xml;googleearth=context.kml,application/vnd.google-earth.kmz;googleearth=context.kmz'
```

The main culprit seems to be the ``;googleearth=context.kml`` in``application/vnd.google-earth.kml+xml;googleearth=context.kml`` and the ``googleearth=context.kmz`` in ``application/vnd.google-earth.kmz;googleearth=context.kmz``.

Quart is only expecting a string of the form ``q=0.9`` in scenarios where a ``;`` is found in an ACCEPT item.

I am not familiar with http ACCEPT specification. Perhaps Quart is correct in its processing of the accept headers against the specification and GoogleEarth is supplying malformed ACCEPT items. If this is the case then this issue can be closed. If not, then it would be nice if the Accept headers got returned without triggering an exception.

**Comment by pgjones** [comment]
Thanks, I think this is a Quart bug, I'll investigate and try to confirm.

**Comment by pgjones** [comment]
It was a bug, that I think I've now fixed. Could you check master (ba2d06828cadfe670ce7f2d0591396818149e8e8) and see if it works for you?

**Comment by claws** [comment]
Test on current master. Seems fixed now. Thanks.

**Comment by pgjones** [comment]
Great, thanks for testing.
