### ISSUE TITLE
Some documentation enhancements and example

### ISSUE THREAD

**Issue by linsomniac** [pgjones/quart#83]
I just wrote a SMTP+Web server using Quart and aiosmtpd, a development mail sink server with web UI to look at messages your software generates.  It's a reimplementation of MailHog, if you are familiar with it.

I struggled with some things such as combining aiosmtpd and quart, implementing the websocket, broadcasting to the websocket...  A few more examples inline or another example to look at would have really helped.

However, this also is my first asyncio program, so maybe these are things that come from there.

However, I wanted to reach out and see if there was interest in me including some more code snippets in the documentation, and/or referring to this code.  It has some e-mail processing code that is a distraction from the core Quart code, but could probably be restructured a bit to "cut to the chase".

If there'd be interest in the changes, I'd be happy to work up a PR on it.  I do need to rework the Config part of the code, and the Quart stuff really takes off around half way through at line 71 here if you'd like to take a look: https://github.com/linsomniac/mailhedgehog/blob/master/mailhedgehog

Thanks, this was my first time using Quart and it was pretty sweet for this project.

**Comment by pgjones** [comment]
Great, I'm glad it worked for you. You could add an [example](https://gitlab.com/pgjones/quart/tree/master/examples) with a [tutorial](https://gitlab.com/pgjones/quart/tree/master/docs) if you think it would fit. Otherwise any (small) improvements you make to the docs will probably make a large difference.

I've added a few hopefully helpful comments to mailhedgehog.

**Comment by linsomniac** [comment]
Thanks for reviewing the code, I made all those suggestions.  I'll start taking a look at some documentation changes and see what I can do about a tutorial.  Thanks!

**Comment by linsomniac** [comment]
I didn't fully understand when I first opened this issue that you were hosting on GitLab and mirroring to Github.  I've submitted some documentation changes over on gitlab in: https://gitlab.com/pgjones/quart/merge_requests/70
