### ISSUE TITLE
help with websocket broadcast beacon

### ISSUE THREAD

**Issue by c2h2** [pgjones/quart#84]
Hi, I am trying with multiuser chatting with this working git:
https://github.com/c2h2learnstocode/quart_websocket_example

I'd like to have a websocket always broadcasting alive beacons, because I have put the beaconer task into a connection handler, I will receive **X multiple beacons** with **X** connections.

where should I put the beconer line?

```
async def beacon_json():
    a={}
    while True:
        dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        a["beacon"]=dt_string
        await asyncio.sleep(5)
        await broadcast(json.dumps(a))

...

@app.websocket('/ws0')
@collect_websocket
async def ws(queue):
    producer = asyncio.create_task(sending(queue))
    consumer = asyncio.create_task(receiving())
    beaconer = asyncio.create_task(beacon_json())  # where to put this line?
    await asyncio.gather(producer, consumer, beaconer)
```
whole file = https://github.com/c2h2learnstocode/quart_websocket_example/blob/master/simple_multi_user_chat.py

**Comment by pgjones** [comment]
I think you are wanting to have a single `beacon_json` task running during the time your app is serving requests. I would use [before_serving and after_serving](https://pgjones.gitlab.io/quart/startup_shutdown.html) to do this,
```python
@app.before_serving
async def startup():
    app.beacon_task = asyncio.create_task(beacon_json())

@app.after_serving
async def shutdown():
    app.beacon_task.cancel()
```

**Comment by c2h2** [comment]
it works perfectly now, thanks!
