### ISSUE TITLE
loading form data

### ISSUE THREAD

**Issue by zabano** [pgjones/quart#9]
Please allow passing of array data to request.form.

As a quick fix i changed [line 159 in wrappers/request.py](https://github.com/pgjones/quart/blob/master/quart/wrappers/request.py#L159) to
`self._form.add(key, value)`.

Cheers,
Omar

**Comment by pgjones** [comment]
Could you elaborate a bit more on what the error/issue is here? I don't really follow...

**Comment by zabano** [comment]
I have a form with a "multiple select" element. When I submit the form, and
I try to access all values using getlist method on request.form, I get a
list containing only the last value. I hope this helps.

**Comment by pgjones** [comment]
Thanks. I think this is fixed in master (b30f81d9308f2c30f78fff69bd7ab08684a4f599), could you confirm?

**Comment by zabano** [comment]
This works! Thanks :)

**Comment by pgjones** [comment]
Great, thanks for checking.
