### ISSUE TITLE
AttributeError: 'Quart' object has no attribute 'asgi_app'

### ISSUE THREAD

**Issue by svenvarkel** [pgjones/quart#90]
I'm trying to attach middleware for checking JWT to my app.

However, upon wrapping middleware to app this way as it's documented an error is thrown:
```
app.asgi_app = ValidateJwtMiddleWare(app.asgi_app)
```

**AttributeError: 'Quart' object has no attribute 'asgi_app'**

Any ideas anybody?

**Comment by pgjones** [comment]
Sorry I've yet to release a version with the `asgi_app` functionality (master will work). ([This](https://gitlab.com/pgjones/quart/issues/157) is semi-related).
