### ISSUE TITLE
ValueError: time data 'Sun, 05 Jan 2020 06:40:05 GMT' does not match format '%Y-%m-%dT%H:%M:%S.%f'

### ISSUE THREAD

**Issue by Yandawl** [pgjones/quart#91]
I get the following error when making a request to /index

![Screen Shot on 2020-01-04 at 13-49-57](https://user-images.githubusercontent.com/8414953/71766602-7f8e7b80-2ef9-11ea-9c01-c9202e4123e9.png)

I am migrating an existing application over from Flask on macOS Catalina

**Comment by pgjones** [comment]
Looks like Flask uses slightly different datetime formats. This is something that could fix itself as Quart replaces the Flask cookies. Otherwise I'll see if the framework can fix it.

**Comment by Yandawl** [comment]
Aye Flask are doing it this way using werkzeug:

![Screen Shot on 2020-01-04 at 14-16-14](https://user-images.githubusercontent.com/8414953/71766876-d5b0ee00-2efc-11ea-812e-64f09e073ca2.png)

https://github.com/pallets/werkzeug/blob/99e1b14bce666ffb67a699d6492af4e6c7bea696/src/werkzeug/http.py#L819

Is this something you will implement a fix for?

Thanks for Quart by the way. We are really in need of an async lib.

**Comment by pgjones** [comment]
Fixed in 69e8854f2f7b135946ce29ba29e01144ccd77630, will be in the next release.

**Comment by pgjones** [comment]
I've decided to change 69e8854f2f7b135946ce29ba29e01144ccd77630 to 408c461d41b5b319d670130510433d4a6f102935 as I don't think the Flask format is the right choice. I'm going to try convince Flask to change, until then Quart will be able to read, but not write Flask compatible data.

**Comment by Yandawl** [comment]
Thanks for your efforts. How does this Flask issue impact me? I just need to be able to successfully run Quart as the synchronous nature of Flask is starting to negatively impact my site without significant overhead.

**Comment by pgjones** [comment]
If you just need to run Quart I don't think this will impact you, this is only an issue if you want to run Flask and Quart and share the session information.
