### ISSUE TITLE
Run in sub thread other than main thread

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [pgjones/quart#96]
Problem: running in sub thread breaks because set_wakeup_fd can only work in main thread.
This is because the following two signal handler:

https://github.com/pgjones/quart/blob/3c601cbf6e80e1f57f99668cf7863bc9288667bb/src/quart/app.py#L1592-L1596

They will throw a RuntimeError when running inside sub thread, thus block Quart from running. Is there any way to allow user to choose whether to setup signal handlers?

**Comment by pgjones** [comment]
Yep, you can use the [`run_task`](https://gitlab.com/pgjones/quart/-/blob/master/src/quart/app.py#L1622) method which returns a coroutine you can await, or run in a loop of you choice.

**Comment by jqqqqqqqqqq** [comment]
Thank you!
