### ISSUE TITLE
New version coroutine issue

### ISSUE THREAD

**Issue by MrYacha** [pgjones/quart#97]
On new 0.11 version I having this while running official flask_ext.py example:
```
Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2020-02-20 13:23:36,983] Running on 127.0.0.1:5000 over http (CTRL + C to quit)
/usr/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py:80: RuntimeWarning: coroutine 'StreamWriter.write' was never awaited
  self.writer.write(event.data)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
On 0.10 version all was fine

**Comment by pgjones** [comment]
These is very strange as [StreamWriter.write is not a coroutine](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.write), do you have any changes to asyncio locally?

**Comment by MrYacha** [comment]
> These is very strange as [StreamWriter.write is not a coroutine](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.write), do you have any changes to asyncio locally?

I don't think so, but I will try run example file on my laptop soon, I will reply after.

**Comment by MrYacha** [comment]
Ok, on other pc example file working well.
